// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_MAP                   TaskType = 1
	TaskType_REDUCE                TaskType = 2
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "MAP",
		2: "REDUCE",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"MAP":                   1,
		"REDUCE":                2,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

type AppState int32

const (
	AppState_APP_STATE_UNSPECIFIED AppState = 0
	AppState_SUBMITTED             AppState = 1
	AppState_RUNNING               AppState = 2
	AppState_FINISHED              AppState = 3
	AppState_FAILED                AppState = 4
	AppState_KILLED                AppState = 5
)

// Enum value maps for AppState.
var (
	AppState_name = map[int32]string{
		0: "APP_STATE_UNSPECIFIED",
		1: "SUBMITTED",
		2: "RUNNING",
		3: "FINISHED",
		4: "FAILED",
		5: "KILLED",
	}
	AppState_value = map[string]int32{
		"APP_STATE_UNSPECIFIED": 0,
		"SUBMITTED":             1,
		"RUNNING":               2,
		"FINISHED":              3,
		"FAILED":                4,
		"KILLED":                5,
	}
)

func (x AppState) Enum() *AppState {
	p := new(AppState)
	*p = x
	return p
}

func (x AppState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[1].Descriptor()
}

func (AppState) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[1]
}

func (x AppState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppState.Descriptor instead.
func (AppState) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

// ContainerState tracks a container's lifecycle.
type ContainerState int32

const (
	ContainerState_CONTAINER_STATE_UNSPECIFIED ContainerState = 0
	ContainerState_CONTAINER_RUNNING           ContainerState = 1
	ContainerState_CONTAINER_COMPLETED         ContainerState = 2
	ContainerState_CONTAINER_FAILED            ContainerState = 3
	ContainerState_CONTAINER_KILLED            ContainerState = 4
)

// Enum value maps for ContainerState.
var (
	ContainerState_name = map[int32]string{
		0: "CONTAINER_STATE_UNSPECIFIED",
		1: "CONTAINER_RUNNING",
		2: "CONTAINER_COMPLETED",
		3: "CONTAINER_FAILED",
		4: "CONTAINER_KILLED",
	}
	ContainerState_value = map[string]int32{
		"CONTAINER_STATE_UNSPECIFIED": 0,
		"CONTAINER_RUNNING":           1,
		"CONTAINER_COMPLETED":         2,
		"CONTAINER_FAILED":            3,
		"CONTAINER_KILLED":            4,
	}
)

func (x ContainerState) Enum() *ContainerState {
	p := new(ContainerState)
	*p = x
	return p
}

func (x ContainerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[2].Descriptor()
}

func (ContainerState) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[2]
}

func (x ContainerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerState.Descriptor instead.
func (ContainerState) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

// BlockInfo describes a single block replica's metadata.
type BlockInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockId         string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Checksum        []byte                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`                                       // SHA-256
	Locations       []string               `protobuf:"bytes,4,rep,name=locations,proto3" json:"locations,omitempty"`                                     // DataNode addresses holding replicas
	GenerationStamp int64                  `protobuf:"varint,5,opt,name=generation_stamp,json=generationStamp,proto3" json:"generation_stamp,omitempty"` // Version stamp for orphaning partial blocks
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockInfo) Reset() {
	*x = BlockInfo{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfo) ProtoMessage() {}

func (x *BlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfo.ProtoReflect.Descriptor instead.
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *BlockInfo) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BlockInfo) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *BlockInfo) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *BlockInfo) GetGenerationStamp() int64 {
	if x != nil {
		return x.GenerationStamp
	}
	return 0
}

// FileInfo describes a file in the namespace.
type FileInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Path              string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes         int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	BlockIds          []string               `protobuf:"bytes,3,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
	ReplicationFactor int32                  `protobuf:"varint,4,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	Permissions       int32                  `protobuf:"varint,5,opt,name=permissions,proto3" json:"permissions,omitempty"`
	IsDirectory       bool                   `protobuf:"varint,6,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	ModificationTime  int64                  `protobuf:"varint,7,opt,name=modification_time,json=modificationTime,proto3" json:"modification_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileInfo) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

func (x *FileInfo) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *FileInfo) GetPermissions() int32 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

func (x *FileInfo) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileInfo) GetModificationTime() int64 {
	if x != nil {
		return x.ModificationTime
	}
	return 0
}

// InputSplit describes a unit of work for a map task.
type InputSplit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	BlockId       string                 `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Locations     []string               `protobuf:"bytes,5,rep,name=locations,proto3" json:"locations,omitempty"` // DataNode addresses holding this block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputSplit) Reset() {
	*x = InputSplit{}
	mi := &file_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputSplit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputSplit) ProtoMessage() {}

func (x *InputSplit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputSplit.ProtoReflect.Descriptor instead.
func (*InputSplit) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *InputSplit) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *InputSplit) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *InputSplit) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *InputSplit) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *InputSplit) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

// ContainerSpec describes resources for a container.
type ContainerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	CpuVcores     int32                  `protobuf:"varint,4,opt,name=cpu_vcores,json=cpuVcores,proto3" json:"cpu_vcores,omitempty"`
	Command       string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerSpec) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerSpec) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ContainerSpec) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ContainerSpec) GetCpuVcores() int32 {
	if x != nil {
		return x.CpuVcores
	}
	return 0
}

func (x *ContainerSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ContainerSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ContainerSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// TaskSpec describes a map or reduce task.
type TaskSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      TaskType               `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=minihadoop.TaskType" json:"task_type,omitempty"`
	InputSplit    *InputSplit            `protobuf:"bytes,3,opt,name=input_split,json=inputSplit,proto3" json:"input_split,omitempty"` // For map tasks
	OutputPath    string                 `protobuf:"bytes,4,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	PartitionId   int32                  `protobuf:"varint,5,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"` // For reduce tasks: which partition to process
	NumReducers   int32                  `protobuf:"varint,6,opt,name=num_reducers,json=numReducers,proto3" json:"num_reducers,omitempty"`
	JobId         string                 `protobuf:"bytes,7,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *TaskSpec) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskSpec) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *TaskSpec) GetInputSplit() *InputSplit {
	if x != nil {
		return x.InputSplit
	}
	return nil
}

func (x *TaskSpec) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *TaskSpec) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *TaskSpec) GetNumReducers() int32 {
	if x != nil {
		return x.NumReducers
	}
	return 0
}

func (x *TaskSpec) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// NodeStatus reports a node's current resource state.
type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TotalMemoryMb int32                  `protobuf:"varint,3,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`
	UsedMemoryMb  int32                  `protobuf:"varint,4,opt,name=used_memory_mb,json=usedMemoryMb,proto3" json:"used_memory_mb,omitempty"`
	TotalCpu      int32                  `protobuf:"varint,5,opt,name=total_cpu,json=totalCpu,proto3" json:"total_cpu,omitempty"`
	UsedCpu       int32                  `protobuf:"varint,6,opt,name=used_cpu,json=usedCpu,proto3" json:"used_cpu,omitempty"`
	NumContainers int32                  `protobuf:"varint,7,opt,name=num_containers,json=numContainers,proto3" json:"num_containers,omitempty"`
	Healthy       bool                   `protobuf:"varint,8,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeStatus) GetTotalMemoryMb() int32 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

func (x *NodeStatus) GetUsedMemoryMb() int32 {
	if x != nil {
		return x.UsedMemoryMb
	}
	return 0
}

func (x *NodeStatus) GetTotalCpu() int32 {
	if x != nil {
		return x.TotalCpu
	}
	return 0
}

func (x *NodeStatus) GetUsedCpu() int32 {
	if x != nil {
		return x.UsedCpu
	}
	return 0
}

func (x *NodeStatus) GetNumContainers() int32 {
	if x != nil {
		return x.NumContainers
	}
	return 0
}

func (x *NodeStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

// ApplicationStatus tracks a submitted application.
type ApplicationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	State         AppState               `protobuf:"varint,2,opt,name=state,proto3,enum=minihadoop.AppState" json:"state,omitempty"`
	AmAddress     string                 `protobuf:"bytes,3,opt,name=am_address,json=amAddress,proto3" json:"am_address,omitempty"`
	Progress      float32                `protobuf:"fixed32,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Diagnostics   string                 `protobuf:"bytes,5,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FinishTime    int64                  `protobuf:"varint,7,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationStatus) Reset() {
	*x = ApplicationStatus{}
	mi := &file_proto_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationStatus) ProtoMessage() {}

func (x *ApplicationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationStatus.ProtoReflect.Descriptor instead.
func (*ApplicationStatus) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{6}
}

func (x *ApplicationStatus) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ApplicationStatus) GetState() AppState {
	if x != nil {
		return x.State
	}
	return AppState_APP_STATE_UNSPECIFIED
}

func (x *ApplicationStatus) GetAmAddress() string {
	if x != nil {
		return x.AmAddress
	}
	return ""
}

func (x *ApplicationStatus) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ApplicationStatus) GetDiagnostics() string {
	if x != nil {
		return x.Diagnostics
	}
	return ""
}

func (x *ApplicationStatus) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ApplicationStatus) GetFinishTime() int64 {
	if x != nil {
		return x.FinishTime
	}
	return 0
}

// LocalityPreference for container allocation.
type LocalityPreference struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PreferredNodes []string               `protobuf:"bytes,1,rep,name=preferred_nodes,json=preferredNodes,proto3" json:"preferred_nodes,omitempty"`
	Relaxed        bool                   `protobuf:"varint,2,opt,name=relaxed,proto3" json:"relaxed,omitempty"` // Allow non-local if preferred unavailable
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalityPreference) Reset() {
	*x = LocalityPreference{}
	mi := &file_proto_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalityPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalityPreference) ProtoMessage() {}

func (x *LocalityPreference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalityPreference.ProtoReflect.Descriptor instead.
func (*LocalityPreference) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{7}
}

func (x *LocalityPreference) GetPreferredNodes() []string {
	if x != nil {
		return x.PreferredNodes
	}
	return nil
}

func (x *LocalityPreference) GetRelaxed() bool {
	if x != nil {
		return x.Relaxed
	}
	return false
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\n" +
	"minihadoop\"\xaa\x01\n" +
	"\tBlockInfo\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\fR\bchecksum\x12\x1c\n" +
	"\tlocations\x18\x04 \x03(\tR\tlocations\x12)\n" +
	"\x10generation_stamp\x18\x05 \x01(\x03R\x0fgenerationStamp\"\xfb\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tblock_ids\x18\x03 \x03(\tR\bblockIds\x12-\n" +
	"\x12replication_factor\x18\x04 \x01(\x05R\x11replicationFactor\x12 \n" +
	"\vpermissions\x18\x05 \x01(\x05R\vpermissions\x12!\n" +
	"\fis_directory\x18\x06 \x01(\bR\visDirectory\x12+\n" +
	"\x11modification_time\x18\a \x01(\x03R\x10modificationTime\"\x92\x01\n" +
	"\n" +
	"InputSplit\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\tR\ablockId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x03R\x06length\x12\x1c\n" +
	"\tlocations\x18\x05 \x03(\tR\tlocations\"\xa3\x02\n" +
	"\rContainerSpec\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x05R\bmemoryMb\x12\x1d\n" +
	"\n" +
	"cpu_vcores\x18\x04 \x01(\x05R\tcpuVcores\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x06 \x03(\tR\x04args\x124\n" +
	"\x03env\x18\a \x03(\v2\".minihadoop.ContainerSpec.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\bTaskSpec\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x121\n" +
	"\ttask_type\x18\x02 \x01(\x0e2\x14.minihadoop.TaskTypeR\btaskType\x127\n" +
	"\vinput_split\x18\x03 \x01(\v2\x16.minihadoop.InputSplitR\n" +
	"inputSplit\x12\x1f\n" +
	"\voutput_path\x18\x04 \x01(\tR\n" +
	"outputPath\x12!\n" +
	"\fpartition_id\x18\x05 \x01(\x05R\vpartitionId\x12!\n" +
	"\fnum_reducers\x18\x06 \x01(\x05R\vnumReducers\x12\x15\n" +
	"\x06job_id\x18\a \x01(\tR\x05jobId\"\x86\x02\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12&\n" +
	"\x0ftotal_memory_mb\x18\x03 \x01(\x05R\rtotalMemoryMb\x12$\n" +
	"\x0eused_memory_mb\x18\x04 \x01(\x05R\fusedMemoryMb\x12\x1b\n" +
	"\ttotal_cpu\x18\x05 \x01(\x05R\btotalCpu\x12\x19\n" +
	"\bused_cpu\x18\x06 \x01(\x05R\ausedCpu\x12%\n" +
	"\x0enum_containers\x18\a \x01(\x05R\rnumContainers\x12\x18\n" +
	"\ahealthy\x18\b \x01(\bR\ahealthy\"\xf3\x01\n" +
	"\x11ApplicationStatus\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.minihadoop.AppStateR\x05state\x12\x1d\n" +
	"\n" +
	"am_address\x18\x03 \x01(\tR\tamAddress\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x02R\bprogress\x12 \n" +
	"\vdiagnostics\x18\x05 \x01(\tR\vdiagnostics\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x1f\n" +
	"\vfinish_time\x18\a \x01(\x03R\n" +
	"finishTime\"W\n" +
	"\x12LocalityPreference\x12'\n" +
	"\x0fpreferred_nodes\x18\x01 \x03(\tR\x0epreferredNodes\x12\x18\n" +
	"\arelaxed\x18\x02 \x01(\bR\arelaxed*:\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03MAP\x10\x01\x12\n" +
	"\n" +
	"\x06REDUCE\x10\x02*g\n" +
	"\bAppState\x12\x19\n" +
	"\x15APP_STATE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSUBMITTED\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\f\n" +
	"\bFINISHED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\n" +
	"\n" +
	"\x06KILLED\x10\x05*\x8d\x01\n" +
	"\x0eContainerState\x12\x1f\n" +
	"\x1bCONTAINER_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONTAINER_RUNNING\x10\x01\x12\x17\n" +
	"\x13CONTAINER_COMPLETED\x10\x02\x12\x14\n" +
	"\x10CONTAINER_FAILED\x10\x03\x12\x14\n" +
	"\x10CONTAINER_KILLED\x10\x04B*Z(github.com/mini-hadoop/mini-hadoop/protob\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_common_proto_goTypes = []any{
	(TaskType)(0),              // 0: minihadoop.TaskType
	(AppState)(0),              // 1: minihadoop.AppState
	(ContainerState)(0),        // 2: minihadoop.ContainerState
	(*BlockInfo)(nil),          // 3: minihadoop.BlockInfo
	(*FileInfo)(nil),           // 4: minihadoop.FileInfo
	(*InputSplit)(nil),         // 5: minihadoop.InputSplit
	(*ContainerSpec)(nil),      // 6: minihadoop.ContainerSpec
	(*TaskSpec)(nil),           // 7: minihadoop.TaskSpec
	(*NodeStatus)(nil),         // 8: minihadoop.NodeStatus
	(*ApplicationStatus)(nil),  // 9: minihadoop.ApplicationStatus
	(*LocalityPreference)(nil), // 10: minihadoop.LocalityPreference
	nil,                        // 11: minihadoop.ContainerSpec.EnvEntry
}
var file_proto_common_proto_depIdxs = []int32{
	11, // 0: minihadoop.ContainerSpec.env:type_name -> minihadoop.ContainerSpec.EnvEntry
	0,  // 1: minihadoop.TaskSpec.task_type:type_name -> minihadoop.TaskType
	5,  // 2: minihadoop.TaskSpec.input_split:type_name -> minihadoop.InputSplit
	1,  // 3: minihadoop.ApplicationStatus.state:type_name -> minihadoop.AppState
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
