// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/datanode.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // Read from this offset within the block
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"` // 0 = read entire block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBlockRequest) Reset() {
	*x = ReadBlockRequest{}
	mi := &file_proto_datanode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBlockRequest) ProtoMessage() {}

func (x *ReadBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datanode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBlockRequest.ProtoReflect.Descriptor instead.
func (*ReadBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_datanode_proto_rawDescGZIP(), []int{0}
}

func (x *ReadBlockRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *ReadBlockRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadBlockRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// DataChunk is a piece of block data (1MB chunks for streaming).
type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"` // Per-chunk checksum for integrity verification
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_proto_datanode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datanode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_proto_datanode_proto_rawDescGZIP(), []int{1}
}

func (x *DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DataChunk) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *DataChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type WriteBlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WriteBlockRequest_Header
	//	*WriteBlockRequest_Chunk
	Payload       isWriteBlockRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBlockRequest) Reset() {
	*x = WriteBlockRequest{}
	mi := &file_proto_datanode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlockRequest) ProtoMessage() {}

func (x *WriteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datanode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlockRequest.ProtoReflect.Descriptor instead.
func (*WriteBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_datanode_proto_rawDescGZIP(), []int{2}
}

func (x *WriteBlockRequest) GetPayload() isWriteBlockRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WriteBlockRequest) GetHeader() *WriteBlockHeader {
	if x != nil {
		if x, ok := x.Payload.(*WriteBlockRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *WriteBlockRequest) GetChunk() *DataChunk {
	if x != nil {
		if x, ok := x.Payload.(*WriteBlockRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isWriteBlockRequest_Payload interface {
	isWriteBlockRequest_Payload()
}

type WriteBlockRequest_Header struct {
	Header *WriteBlockHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"` // First message: metadata
}

type WriteBlockRequest_Chunk struct {
	Chunk *DataChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // Subsequent messages: data chunks
}

func (*WriteBlockRequest_Header) isWriteBlockRequest_Payload() {}

func (*WriteBlockRequest_Chunk) isWriteBlockRequest_Payload() {}

type WriteBlockHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockId         string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	GenerationStamp int64                  `protobuf:"varint,2,opt,name=generation_stamp,json=generationStamp,proto3" json:"generation_stamp,omitempty"`
	Pipeline        []string               `protobuf:"bytes,3,rep,name=pipeline,proto3" json:"pipeline,omitempty"`                                 // Remaining DataNodes in pipeline (forwarding targets)
	PipelineIndex   int32                  `protobuf:"varint,4,opt,name=pipeline_index,json=pipelineIndex,proto3" json:"pipeline_index,omitempty"` // This node's position in the pipeline
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WriteBlockHeader) Reset() {
	*x = WriteBlockHeader{}
	mi := &file_proto_datanode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlockHeader) ProtoMessage() {}

func (x *WriteBlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datanode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlockHeader.ProtoReflect.Descriptor instead.
func (*WriteBlockHeader) Descriptor() ([]byte, []int) {
	return file_proto_datanode_proto_rawDescGZIP(), []int{3}
}

func (x *WriteBlockHeader) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *WriteBlockHeader) GetGenerationStamp() int64 {
	if x != nil {
		return x.GenerationStamp
	}
	return 0
}

func (x *WriteBlockHeader) GetPipeline() []string {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *WriteBlockHeader) GetPipelineIndex() int32 {
	if x != nil {
		return x.PipelineIndex
	}
	return 0
}

type WriteBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BytesWritten  int64                  `protobuf:"varint,2,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"` // SHA-256 of the entire block
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBlockResponse) Reset() {
	*x = WriteBlockResponse{}
	mi := &file_proto_datanode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlockResponse) ProtoMessage() {}

func (x *WriteBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datanode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlockResponse.ProtoReflect.Descriptor instead.
func (*WriteBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_datanode_proto_rawDescGZIP(), []int{4}
}

func (x *WriteBlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteBlockResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *WriteBlockResponse) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *WriteBlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlockRequest) Reset() {
	*x = DeleteBlockRequest{}
	mi := &file_proto_datanode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockRequest) ProtoMessage() {}

func (x *DeleteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datanode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_datanode_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBlockRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

type DeleteBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlockResponse) Reset() {
	*x = DeleteBlockResponse{}
	mi := &file_proto_datanode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockResponse) ProtoMessage() {}

func (x *DeleteBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datanode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_datanode_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TransferBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	SourceAddress string                 `protobuf:"bytes,2,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"` // DataNode address to copy from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBlockRequest) Reset() {
	*x = TransferBlockRequest{}
	mi := &file_proto_datanode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBlockRequest) ProtoMessage() {}

func (x *TransferBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datanode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBlockRequest.ProtoReflect.Descriptor instead.
func (*TransferBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_datanode_proto_rawDescGZIP(), []int{7}
}

func (x *TransferBlockRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *TransferBlockRequest) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

type TransferBlockResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BytesTransferred int64                  `protobuf:"varint,2,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	Error            string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferBlockResponse) Reset() {
	*x = TransferBlockResponse{}
	mi := &file_proto_datanode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBlockResponse) ProtoMessage() {}

func (x *TransferBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datanode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBlockResponse.ProtoReflect.Descriptor instead.
func (*TransferBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_datanode_proto_rawDescGZIP(), []int{8}
}

func (x *TransferBlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferBlockResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *TransferBlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_datanode_proto protoreflect.FileDescriptor

const file_proto_datanode_proto_rawDesc = "" +
	"\n" +
	"\x14proto/datanode.proto\x12\n" +
	"minihadoop\"]\n" +
	"\x10ReadBlockRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"l\n" +
	"\tDataChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\fR\bchecksum\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\"\x85\x01\n" +
	"\x11WriteBlockRequest\x126\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.minihadoop.WriteBlockHeaderH\x00R\x06header\x12-\n" +
	"\x05chunk\x18\x02 \x01(\v2\x15.minihadoop.DataChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"\x9b\x01\n" +
	"\x10WriteBlockHeader\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12)\n" +
	"\x10generation_stamp\x18\x02 \x01(\x03R\x0fgenerationStamp\x12\x1a\n" +
	"\bpipeline\x18\x03 \x03(\tR\bpipeline\x12%\n" +
	"\x0epipeline_index\x18\x04 \x01(\x05R\rpipelineIndex\"\x85\x01\n" +
	"\x12WriteBlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rbytes_written\x18\x02 \x01(\x03R\fbytesWritten\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\fR\bchecksum\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"/\n" +
	"\x12DeleteBlockRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\"E\n" +
	"\x13DeleteBlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"X\n" +
	"\x14TransferBlockRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12%\n" +
	"\x0esource_address\x18\x02 \x01(\tR\rsourceAddress\"t\n" +
	"\x15TransferBlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x11bytes_transferred\x18\x02 \x01(\x03R\x10bytesTransferred\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xca\x02\n" +
	"\x0fDataNodeService\x12B\n" +
	"\tReadBlock\x12\x1c.minihadoop.ReadBlockRequest\x1a\x15.minihadoop.DataChunk0\x01\x12M\n" +
	"\n" +
	"WriteBlock\x12\x1d.minihadoop.WriteBlockRequest\x1a\x1e.minihadoop.WriteBlockResponse(\x01\x12N\n" +
	"\vDeleteBlock\x12\x1e.minihadoop.DeleteBlockRequest\x1a\x1f.minihadoop.DeleteBlockResponse\x12T\n" +
	"\rTransferBlock\x12 .minihadoop.TransferBlockRequest\x1a!.minihadoop.TransferBlockResponseB*Z(github.com/mini-hadoop/mini-hadoop/protob\x06proto3"

var (
	file_proto_datanode_proto_rawDescOnce sync.Once
	file_proto_datanode_proto_rawDescData []byte
)

func file_proto_datanode_proto_rawDescGZIP() []byte {
	file_proto_datanode_proto_rawDescOnce.Do(func() {
		file_proto_datanode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_datanode_proto_rawDesc), len(file_proto_datanode_proto_rawDesc)))
	})
	return file_proto_datanode_proto_rawDescData
}

var file_proto_datanode_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_datanode_proto_goTypes = []any{
	(*ReadBlockRequest)(nil),      // 0: minihadoop.ReadBlockRequest
	(*DataChunk)(nil),             // 1: minihadoop.DataChunk
	(*WriteBlockRequest)(nil),     // 2: minihadoop.WriteBlockRequest
	(*WriteBlockHeader)(nil),      // 3: minihadoop.WriteBlockHeader
	(*WriteBlockResponse)(nil),    // 4: minihadoop.WriteBlockResponse
	(*DeleteBlockRequest)(nil),    // 5: minihadoop.DeleteBlockRequest
	(*DeleteBlockResponse)(nil),   // 6: minihadoop.DeleteBlockResponse
	(*TransferBlockRequest)(nil),  // 7: minihadoop.TransferBlockRequest
	(*TransferBlockResponse)(nil), // 8: minihadoop.TransferBlockResponse
}
var file_proto_datanode_proto_depIdxs = []int32{
	3, // 0: minihadoop.WriteBlockRequest.header:type_name -> minihadoop.WriteBlockHeader
	1, // 1: minihadoop.WriteBlockRequest.chunk:type_name -> minihadoop.DataChunk
	0, // 2: minihadoop.DataNodeService.ReadBlock:input_type -> minihadoop.ReadBlockRequest
	2, // 3: minihadoop.DataNodeService.WriteBlock:input_type -> minihadoop.WriteBlockRequest
	5, // 4: minihadoop.DataNodeService.DeleteBlock:input_type -> minihadoop.DeleteBlockRequest
	7, // 5: minihadoop.DataNodeService.TransferBlock:input_type -> minihadoop.TransferBlockRequest
	1, // 6: minihadoop.DataNodeService.ReadBlock:output_type -> minihadoop.DataChunk
	4, // 7: minihadoop.DataNodeService.WriteBlock:output_type -> minihadoop.WriteBlockResponse
	6, // 8: minihadoop.DataNodeService.DeleteBlock:output_type -> minihadoop.DeleteBlockResponse
	8, // 9: minihadoop.DataNodeService.TransferBlock:output_type -> minihadoop.TransferBlockResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_datanode_proto_init() }
func file_proto_datanode_proto_init() {
	if File_proto_datanode_proto != nil {
		return
	}
	file_proto_datanode_proto_msgTypes[2].OneofWrappers = []any{
		(*WriteBlockRequest_Header)(nil),
		(*WriteBlockRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_datanode_proto_rawDesc), len(file_proto_datanode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_datanode_proto_goTypes,
		DependencyIndexes: file_proto_datanode_proto_depIdxs,
		MessageInfos:      file_proto_datanode_proto_msgTypes,
	}.Build()
	File_proto_datanode_proto = out.File
	file_proto_datanode_proto_goTypes = nil
	file_proto_datanode_proto_depIdxs = nil
}
