// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.2
// source: proto/datanode.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataNodeService_ReadBlock_FullMethodName     = "/minihadoop.DataNodeService/ReadBlock"
	DataNodeService_WriteBlock_FullMethodName    = "/minihadoop.DataNodeService/WriteBlock"
	DataNodeService_DeleteBlock_FullMethodName   = "/minihadoop.DataNodeService/DeleteBlock"
	DataNodeService_TransferBlock_FullMethodName = "/minihadoop.DataNodeService/TransferBlock"
)

// DataNodeServiceClient is the client API for DataNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataNodeServiceClient interface {
	// ReadBlock streams block data from DataNode to client.
	ReadBlock(ctx context.Context, in *ReadBlockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	// WriteBlock receives block data and optionally forwards to next in pipeline.
	WriteBlock(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteBlockRequest, WriteBlockResponse], error)
	// DeleteBlock removes a block from local storage.
	DeleteBlock(ctx context.Context, in *DeleteBlockRequest, opts ...grpc.CallOption) (*DeleteBlockResponse, error)
	// TransferBlock copies a block from another DataNode (for re-replication).
	TransferBlock(ctx context.Context, in *TransferBlockRequest, opts ...grpc.CallOption) (*TransferBlockResponse, error)
}

type dataNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNodeServiceClient(cc grpc.ClientConnInterface) DataNodeServiceClient {
	return &dataNodeServiceClient{cc}
}

func (c *dataNodeServiceClient) ReadBlock(ctx context.Context, in *ReadBlockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataNodeService_ServiceDesc.Streams[0], DataNodeService_ReadBlock_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadBlockRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNodeService_ReadBlockClient = grpc.ServerStreamingClient[DataChunk]

func (c *dataNodeServiceClient) WriteBlock(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteBlockRequest, WriteBlockResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataNodeService_ServiceDesc.Streams[1], DataNodeService_WriteBlock_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteBlockRequest, WriteBlockResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNodeService_WriteBlockClient = grpc.ClientStreamingClient[WriteBlockRequest, WriteBlockResponse]

func (c *dataNodeServiceClient) DeleteBlock(ctx context.Context, in *DeleteBlockRequest, opts ...grpc.CallOption) (*DeleteBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBlockResponse)
	err := c.cc.Invoke(ctx, DataNodeService_DeleteBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeServiceClient) TransferBlock(ctx context.Context, in *TransferBlockRequest, opts ...grpc.CallOption) (*TransferBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferBlockResponse)
	err := c.cc.Invoke(ctx, DataNodeService_TransferBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataNodeServiceServer is the server API for DataNodeService service.
// All implementations must embed UnimplementedDataNodeServiceServer
// for forward compatibility.
type DataNodeServiceServer interface {
	// ReadBlock streams block data from DataNode to client.
	ReadBlock(*ReadBlockRequest, grpc.ServerStreamingServer[DataChunk]) error
	// WriteBlock receives block data and optionally forwards to next in pipeline.
	WriteBlock(grpc.ClientStreamingServer[WriteBlockRequest, WriteBlockResponse]) error
	// DeleteBlock removes a block from local storage.
	DeleteBlock(context.Context, *DeleteBlockRequest) (*DeleteBlockResponse, error)
	// TransferBlock copies a block from another DataNode (for re-replication).
	TransferBlock(context.Context, *TransferBlockRequest) (*TransferBlockResponse, error)
	mustEmbedUnimplementedDataNodeServiceServer()
}

// UnimplementedDataNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataNodeServiceServer struct{}

func (UnimplementedDataNodeServiceServer) ReadBlock(*ReadBlockRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadBlock not implemented")
}
func (UnimplementedDataNodeServiceServer) WriteBlock(grpc.ClientStreamingServer[WriteBlockRequest, WriteBlockResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteBlock not implemented")
}
func (UnimplementedDataNodeServiceServer) DeleteBlock(context.Context, *DeleteBlockRequest) (*DeleteBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBlock not implemented")
}
func (UnimplementedDataNodeServiceServer) TransferBlock(context.Context, *TransferBlockRequest) (*TransferBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferBlock not implemented")
}
func (UnimplementedDataNodeServiceServer) mustEmbedUnimplementedDataNodeServiceServer() {}
func (UnimplementedDataNodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeDataNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNodeServiceServer will
// result in compilation errors.
type UnsafeDataNodeServiceServer interface {
	mustEmbedUnimplementedDataNodeServiceServer()
}

func RegisterDataNodeServiceServer(s grpc.ServiceRegistrar, srv DataNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedDataNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataNodeService_ServiceDesc, srv)
}

func _DataNodeService_ReadBlock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadBlockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataNodeServiceServer).ReadBlock(m, &grpc.GenericServerStream[ReadBlockRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNodeService_ReadBlockServer = grpc.ServerStreamingServer[DataChunk]

func _DataNodeService_WriteBlock_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataNodeServiceServer).WriteBlock(&grpc.GenericServerStream[WriteBlockRequest, WriteBlockResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNodeService_WriteBlockServer = grpc.ClientStreamingServer[WriteBlockRequest, WriteBlockResponse]

func _DataNodeService_DeleteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServiceServer).DeleteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeService_DeleteBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServiceServer).DeleteBlock(ctx, req.(*DeleteBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNodeService_TransferBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServiceServer).TransferBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeService_TransferBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServiceServer).TransferBlock(ctx, req.(*TransferBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataNodeService_ServiceDesc is the grpc.ServiceDesc for DataNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minihadoop.DataNodeService",
	HandlerType: (*DataNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteBlock",
			Handler:    _DataNodeService_DeleteBlock_Handler,
		},
		{
			MethodName: "TransferBlock",
			Handler:    _DataNodeService_TransferBlock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadBlock",
			Handler:       _DataNodeService_ReadBlock_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteBlock",
			Handler:       _DataNodeService_WriteBlock_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/datanode.proto",
}
