// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/namenode.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	CommandType_REPLICATE                CommandType = 1 // Copy block to target_nodes
	CommandType_DELETE                   CommandType = 2 // Delete block locally
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "REPLICATE",
		2: "DELETE",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED": 0,
		"REPLICATE":                1,
		"DELETE":                   2,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_namenode_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_namenode_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{0}
}

type CreateFileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Path              string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ReplicationFactor int32                  `protobuf:"varint,2,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"` // 0 = use default (3)
	BlockSize         int64                  `protobuf:"varint,3,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`                         // 0 = use default (128MB)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_proto_namenode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateFileRequest) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *CreateFileRequest) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_proto_namenode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBlockLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockLocationsRequest) Reset() {
	*x = GetBlockLocationsRequest{}
	mi := &file_proto_namenode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockLocationsRequest) ProtoMessage() {}

func (x *GetBlockLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetBlockLocationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlockLocationsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetBlockLocationsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetBlockLocationsRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type GetBlockLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockInfo           `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockLocationsResponse) Reset() {
	*x = GetBlockLocationsResponse{}
	mi := &file_proto_namenode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockLocationsResponse) ProtoMessage() {}

func (x *GetBlockLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetBlockLocationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlockLocationsResponse) GetBlocks() []*BlockInfo {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *GetBlockLocationsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ClientAddress string                 `protobuf:"bytes,2,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"` // For locality-based DN selection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlockRequest) Reset() {
	*x = AddBlockRequest{}
	mi := &file_proto_namenode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlockRequest) ProtoMessage() {}

func (x *AddBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlockRequest.ProtoReflect.Descriptor instead.
func (*AddBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{4}
}

func (x *AddBlockRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddBlockRequest) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

type AddBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BlockInfo             `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Pipeline      []string               `protobuf:"bytes,2,rep,name=pipeline,proto3" json:"pipeline,omitempty"` // Ordered list of DataNode addresses for pipeline write
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlockResponse) Reset() {
	*x = AddBlockResponse{}
	mi := &file_proto_namenode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlockResponse) ProtoMessage() {}

func (x *AddBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlockResponse.ProtoReflect.Descriptor instead.
func (*AddBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{5}
}

func (x *AddBlockResponse) GetBlock() *BlockInfo {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *AddBlockResponse) GetPipeline() []string {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *AddBlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BlockIds      []string               `protobuf:"bytes,2,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFileRequest) Reset() {
	*x = CompleteFileRequest{}
	mi := &file_proto_namenode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFileRequest) ProtoMessage() {}

func (x *CompleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFileRequest.ProtoReflect.Descriptor instead.
func (*CompleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CompleteFileRequest) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

type CompleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFileResponse) Reset() {
	*x = CompleteFileResponse{}
	mi := &file_proto_namenode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFileResponse) ProtoMessage() {}

func (x *CompleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFileResponse.ProtoReflect.Descriptor instead.
func (*CompleteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_namenode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteFileRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_proto_namenode_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryRequest) Reset() {
	*x = ListDirectoryRequest{}
	mi := &file_proto_namenode_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryRequest) ProtoMessage() {}

func (x *ListDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ListDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{10}
}

func (x *ListDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileInfo            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryResponse) Reset() {
	*x = ListDirectoryResponse{}
	mi := &file_proto_namenode_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryResponse) ProtoMessage() {}

func (x *ListDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ListDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{11}
}

func (x *ListDirectoryResponse) GetEntries() []*FileInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListDirectoryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MkDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	CreateParents bool                   `protobuf:"varint,2,opt,name=create_parents,json=createParents,proto3" json:"create_parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkDirRequest) Reset() {
	*x = MkDirRequest{}
	mi := &file_proto_namenode_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkDirRequest) ProtoMessage() {}

func (x *MkDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkDirRequest.ProtoReflect.Descriptor instead.
func (*MkDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{12}
}

func (x *MkDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkDirRequest) GetCreateParents() bool {
	if x != nil {
		return x.CreateParents
	}
	return false
}

type MkDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkDirResponse) Reset() {
	*x = MkDirResponse{}
	mi := &file_proto_namenode_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkDirResponse) ProtoMessage() {}

func (x *MkDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkDirResponse.ProtoReflect.Descriptor instead.
func (*MkDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{13}
}

func (x *MkDirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MkDirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_proto_namenode_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{14}
}

func (x *GetFileInfoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *FileInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoResponse) Reset() {
	*x = GetFileInfoResponse{}
	mi := &file_proto_namenode_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResponse) ProtoMessage() {}

func (x *GetFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{15}
}

func (x *GetFileInfoResponse) GetInfo() *FileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetFileInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegisterDataNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // host:port for data transfer
	CapacityBytes int64                  `protobuf:"varint,3,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDataNodeRequest) Reset() {
	*x = RegisterDataNodeRequest{}
	mi := &file_proto_namenode_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDataNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataNodeRequest) ProtoMessage() {}

func (x *RegisterDataNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterDataNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterDataNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterDataNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterDataNodeRequest) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

type RegisterDataNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDataNodeResponse) Reset() {
	*x = RegisterDataNodeResponse{}
	mi := &file_proto_namenode_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDataNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataNodeResponse) ProtoMessage() {}

func (x *RegisterDataNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterDataNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterDataNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterDataNodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UsedBytes      int64                  `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	AvailableBytes int64                  `protobuf:"varint,3,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	NumBlocks      int32                  `protobuf:"varint,4,opt,name=num_blocks,json=numBlocks,proto3" json:"num_blocks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_namenode_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *HeartbeatRequest) GetNumBlocks() int32 {
	if x != nil {
		return x.NumBlocks
	}
	return 0
}

// HeartbeatResponse can carry commands from NameNode to DataNode.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*BlockCommand        `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_namenode_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{19}
}

func (x *HeartbeatResponse) GetCommands() []*BlockCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type BlockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=minihadoop.CommandType" json:"type,omitempty"`
	BlockId       string                 `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	TargetNodes   []string               `protobuf:"bytes,3,rep,name=target_nodes,json=targetNodes,proto3" json:"target_nodes,omitempty"` // For replication: where to send the block
	SourceNode    string                 `protobuf:"bytes,4,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`    // For replication: where to get the block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCommand) Reset() {
	*x = BlockCommand{}
	mi := &file_proto_namenode_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCommand) ProtoMessage() {}

func (x *BlockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCommand.ProtoReflect.Descriptor instead.
func (*BlockCommand) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{20}
}

func (x *BlockCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *BlockCommand) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockCommand) GetTargetNodes() []string {
	if x != nil {
		return x.TargetNodes
	}
	return nil
}

func (x *BlockCommand) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

type BlockReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Blocks        []*BlockReportEntry    `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockReportRequest) Reset() {
	*x = BlockReportRequest{}
	mi := &file_proto_namenode_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReportRequest) ProtoMessage() {}

func (x *BlockReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReportRequest.ProtoReflect.Descriptor instead.
func (*BlockReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{21}
}

func (x *BlockReportRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BlockReportRequest) GetBlocks() []*BlockReportEntry {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type BlockReportEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockId         string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	GenerationStamp int64                  `protobuf:"varint,3,opt,name=generation_stamp,json=generationStamp,proto3" json:"generation_stamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockReportEntry) Reset() {
	*x = BlockReportEntry{}
	mi := &file_proto_namenode_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReportEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReportEntry) ProtoMessage() {}

func (x *BlockReportEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReportEntry.ProtoReflect.Descriptor instead.
func (*BlockReportEntry) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{22}
}

func (x *BlockReportEntry) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockReportEntry) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BlockReportEntry) GetGenerationStamp() int64 {
	if x != nil {
		return x.GenerationStamp
	}
	return 0
}

type BlockReportResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlocksToDelete []string               `protobuf:"bytes,1,rep,name=blocks_to_delete,json=blocksToDelete,proto3" json:"blocks_to_delete,omitempty"` // Blocks the DN should remove (orphaned)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockReportResponse) Reset() {
	*x = BlockReportResponse{}
	mi := &file_proto_namenode_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReportResponse) ProtoMessage() {}

func (x *BlockReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReportResponse.ProtoReflect.Descriptor instead.
func (*BlockReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{23}
}

func (x *BlockReportResponse) GetBlocksToDelete() []string {
	if x != nil {
		return x.BlocksToDelete
	}
	return nil
}

var File_proto_namenode_proto protoreflect.FileDescriptor

const file_proto_namenode_proto_rawDesc = "" +
	"\n" +
	"\x14proto/namenode.proto\x12\n" +
	"minihadoop\x1a\x12proto/common.proto\"u\n" +
	"\x11CreateFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12-\n" +
	"\x12replication_factor\x18\x02 \x01(\x05R\x11replicationFactor\x12\x1d\n" +
	"\n" +
	"block_size\x18\x03 \x01(\x03R\tblockSize\"D\n" +
	"\x12CreateFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"^\n" +
	"\x18GetBlockLocationsRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"`\n" +
	"\x19GetBlockLocationsResponse\x12-\n" +
	"\x06blocks\x18\x01 \x03(\v2\x15.minihadoop.BlockInfoR\x06blocks\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"L\n" +
	"\x0fAddBlockRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12%\n" +
	"\x0eclient_address\x18\x02 \x01(\tR\rclientAddress\"q\n" +
	"\x10AddBlockResponse\x12+\n" +
	"\x05block\x18\x01 \x01(\v2\x15.minihadoop.BlockInfoR\x05block\x12\x1a\n" +
	"\bpipeline\x18\x02 \x03(\tR\bpipeline\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"F\n" +
	"\x13CompleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tblock_ids\x18\x02 \x03(\tR\bblockIds\"F\n" +
	"\x14CompleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"E\n" +
	"\x11DeleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"D\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"*\n" +
	"\x14ListDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"]\n" +
	"\x15ListDirectoryResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.minihadoop.FileInfoR\aentries\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"I\n" +
	"\fMkDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12%\n" +
	"\x0ecreate_parents\x18\x02 \x01(\bR\rcreateParents\"?\n" +
	"\rMkDirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x12GetFileInfoRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"U\n" +
	"\x13GetFileInfoResponse\x12(\n" +
	"\x04info\x18\x01 \x01(\v2\x14.minihadoop.FileInfoR\x04info\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"s\n" +
	"\x17RegisterDataNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12%\n" +
	"\x0ecapacity_bytes\x18\x03 \x01(\x03R\rcapacityBytes\"J\n" +
	"\x18RegisterDataNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x92\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x03R\tusedBytes\x12'\n" +
	"\x0favailable_bytes\x18\x03 \x01(\x03R\x0eavailableBytes\x12\x1d\n" +
	"\n" +
	"num_blocks\x18\x04 \x01(\x05R\tnumBlocks\"I\n" +
	"\x11HeartbeatResponse\x124\n" +
	"\bcommands\x18\x01 \x03(\v2\x18.minihadoop.BlockCommandR\bcommands\"\x9a\x01\n" +
	"\fBlockCommand\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.minihadoop.CommandTypeR\x04type\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\tR\ablockId\x12!\n" +
	"\ftarget_nodes\x18\x03 \x03(\tR\vtargetNodes\x12\x1f\n" +
	"\vsource_node\x18\x04 \x01(\tR\n" +
	"sourceNode\"c\n" +
	"\x12BlockReportRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x124\n" +
	"\x06blocks\x18\x02 \x03(\v2\x1c.minihadoop.BlockReportEntryR\x06blocks\"w\n" +
	"\x10BlockReportEntry\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12)\n" +
	"\x10generation_stamp\x18\x03 \x01(\x03R\x0fgenerationStamp\"?\n" +
	"\x13BlockReportResponse\x12(\n" +
	"\x10blocks_to_delete\x18\x01 \x03(\tR\x0eblocksToDelete*F\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tREPLICATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x022\x84\a\n" +
	"\x0fNameNodeService\x12K\n" +
	"\n" +
	"CreateFile\x12\x1d.minihadoop.CreateFileRequest\x1a\x1e.minihadoop.CreateFileResponse\x12`\n" +
	"\x11GetBlockLocations\x12$.minihadoop.GetBlockLocationsRequest\x1a%.minihadoop.GetBlockLocationsResponse\x12E\n" +
	"\bAddBlock\x12\x1b.minihadoop.AddBlockRequest\x1a\x1c.minihadoop.AddBlockResponse\x12Q\n" +
	"\fCompleteFile\x12\x1f.minihadoop.CompleteFileRequest\x1a .minihadoop.CompleteFileResponse\x12K\n" +
	"\n" +
	"DeleteFile\x12\x1d.minihadoop.DeleteFileRequest\x1a\x1e.minihadoop.DeleteFileResponse\x12T\n" +
	"\rListDirectory\x12 .minihadoop.ListDirectoryRequest\x1a!.minihadoop.ListDirectoryResponse\x12<\n" +
	"\x05MkDir\x12\x18.minihadoop.MkDirRequest\x1a\x19.minihadoop.MkDirResponse\x12N\n" +
	"\vGetFileInfo\x12\x1e.minihadoop.GetFileInfoRequest\x1a\x1f.minihadoop.GetFileInfoResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.minihadoop.HeartbeatRequest\x1a\x1d.minihadoop.HeartbeatResponse\x12N\n" +
	"\vBlockReport\x12\x1e.minihadoop.BlockReportRequest\x1a\x1f.minihadoop.BlockReportResponse\x12]\n" +
	"\x10RegisterDataNode\x12#.minihadoop.RegisterDataNodeRequest\x1a$.minihadoop.RegisterDataNodeResponseB*Z(github.com/mini-hadoop/mini-hadoop/protob\x06proto3"

var (
	file_proto_namenode_proto_rawDescOnce sync.Once
	file_proto_namenode_proto_rawDescData []byte
)

func file_proto_namenode_proto_rawDescGZIP() []byte {
	file_proto_namenode_proto_rawDescOnce.Do(func() {
		file_proto_namenode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_namenode_proto_rawDesc), len(file_proto_namenode_proto_rawDesc)))
	})
	return file_proto_namenode_proto_rawDescData
}

var file_proto_namenode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_namenode_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_namenode_proto_goTypes = []any{
	(CommandType)(0),                  // 0: minihadoop.CommandType
	(*CreateFileRequest)(nil),         // 1: minihadoop.CreateFileRequest
	(*CreateFileResponse)(nil),        // 2: minihadoop.CreateFileResponse
	(*GetBlockLocationsRequest)(nil),  // 3: minihadoop.GetBlockLocationsRequest
	(*GetBlockLocationsResponse)(nil), // 4: minihadoop.GetBlockLocationsResponse
	(*AddBlockRequest)(nil),           // 5: minihadoop.AddBlockRequest
	(*AddBlockResponse)(nil),          // 6: minihadoop.AddBlockResponse
	(*CompleteFileRequest)(nil),       // 7: minihadoop.CompleteFileRequest
	(*CompleteFileResponse)(nil),      // 8: minihadoop.CompleteFileResponse
	(*DeleteFileRequest)(nil),         // 9: minihadoop.DeleteFileRequest
	(*DeleteFileResponse)(nil),        // 10: minihadoop.DeleteFileResponse
	(*ListDirectoryRequest)(nil),      // 11: minihadoop.ListDirectoryRequest
	(*ListDirectoryResponse)(nil),     // 12: minihadoop.ListDirectoryResponse
	(*MkDirRequest)(nil),              // 13: minihadoop.MkDirRequest
	(*MkDirResponse)(nil),             // 14: minihadoop.MkDirResponse
	(*GetFileInfoRequest)(nil),        // 15: minihadoop.GetFileInfoRequest
	(*GetFileInfoResponse)(nil),       // 16: minihadoop.GetFileInfoResponse
	(*RegisterDataNodeRequest)(nil),   // 17: minihadoop.RegisterDataNodeRequest
	(*RegisterDataNodeResponse)(nil),  // 18: minihadoop.RegisterDataNodeResponse
	(*HeartbeatRequest)(nil),          // 19: minihadoop.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 20: minihadoop.HeartbeatResponse
	(*BlockCommand)(nil),              // 21: minihadoop.BlockCommand
	(*BlockReportRequest)(nil),        // 22: minihadoop.BlockReportRequest
	(*BlockReportEntry)(nil),          // 23: minihadoop.BlockReportEntry
	(*BlockReportResponse)(nil),       // 24: minihadoop.BlockReportResponse
	(*BlockInfo)(nil),                 // 25: minihadoop.BlockInfo
	(*FileInfo)(nil),                  // 26: minihadoop.FileInfo
}
var file_proto_namenode_proto_depIdxs = []int32{
	25, // 0: minihadoop.GetBlockLocationsResponse.blocks:type_name -> minihadoop.BlockInfo
	25, // 1: minihadoop.AddBlockResponse.block:type_name -> minihadoop.BlockInfo
	26, // 2: minihadoop.ListDirectoryResponse.entries:type_name -> minihadoop.FileInfo
	26, // 3: minihadoop.GetFileInfoResponse.info:type_name -> minihadoop.FileInfo
	21, // 4: minihadoop.HeartbeatResponse.commands:type_name -> minihadoop.BlockCommand
	0,  // 5: minihadoop.BlockCommand.type:type_name -> minihadoop.CommandType
	23, // 6: minihadoop.BlockReportRequest.blocks:type_name -> minihadoop.BlockReportEntry
	1,  // 7: minihadoop.NameNodeService.CreateFile:input_type -> minihadoop.CreateFileRequest
	3,  // 8: minihadoop.NameNodeService.GetBlockLocations:input_type -> minihadoop.GetBlockLocationsRequest
	5,  // 9: minihadoop.NameNodeService.AddBlock:input_type -> minihadoop.AddBlockRequest
	7,  // 10: minihadoop.NameNodeService.CompleteFile:input_type -> minihadoop.CompleteFileRequest
	9,  // 11: minihadoop.NameNodeService.DeleteFile:input_type -> minihadoop.DeleteFileRequest
	11, // 12: minihadoop.NameNodeService.ListDirectory:input_type -> minihadoop.ListDirectoryRequest
	13, // 13: minihadoop.NameNodeService.MkDir:input_type -> minihadoop.MkDirRequest
	15, // 14: minihadoop.NameNodeService.GetFileInfo:input_type -> minihadoop.GetFileInfoRequest
	19, // 15: minihadoop.NameNodeService.Heartbeat:input_type -> minihadoop.HeartbeatRequest
	22, // 16: minihadoop.NameNodeService.BlockReport:input_type -> minihadoop.BlockReportRequest
	17, // 17: minihadoop.NameNodeService.RegisterDataNode:input_type -> minihadoop.RegisterDataNodeRequest
	2,  // 18: minihadoop.NameNodeService.CreateFile:output_type -> minihadoop.CreateFileResponse
	4,  // 19: minihadoop.NameNodeService.GetBlockLocations:output_type -> minihadoop.GetBlockLocationsResponse
	6,  // 20: minihadoop.NameNodeService.AddBlock:output_type -> minihadoop.AddBlockResponse
	8,  // 21: minihadoop.NameNodeService.CompleteFile:output_type -> minihadoop.CompleteFileResponse
	10, // 22: minihadoop.NameNodeService.DeleteFile:output_type -> minihadoop.DeleteFileResponse
	12, // 23: minihadoop.NameNodeService.ListDirectory:output_type -> minihadoop.ListDirectoryResponse
	14, // 24: minihadoop.NameNodeService.MkDir:output_type -> minihadoop.MkDirResponse
	16, // 25: minihadoop.NameNodeService.GetFileInfo:output_type -> minihadoop.GetFileInfoResponse
	20, // 26: minihadoop.NameNodeService.Heartbeat:output_type -> minihadoop.HeartbeatResponse
	24, // 27: minihadoop.NameNodeService.BlockReport:output_type -> minihadoop.BlockReportResponse
	18, // 28: minihadoop.NameNodeService.RegisterDataNode:output_type -> minihadoop.RegisterDataNodeResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_namenode_proto_init() }
func file_proto_namenode_proto_init() {
	if File_proto_namenode_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_namenode_proto_rawDesc), len(file_proto_namenode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_namenode_proto_goTypes,
		DependencyIndexes: file_proto_namenode_proto_depIdxs,
		EnumInfos:         file_proto_namenode_proto_enumTypes,
		MessageInfos:      file_proto_namenode_proto_msgTypes,
	}.Build()
	File_proto_namenode_proto = out.File
	file_proto_namenode_proto_goTypes = nil
	file_proto_namenode_proto_depIdxs = nil
}
