// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/nodemanager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LaunchContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ContainerSpec         `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchContainerRequest) Reset() {
	*x = LaunchContainerRequest{}
	mi := &file_proto_nodemanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchContainerRequest) ProtoMessage() {}

func (x *LaunchContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodemanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchContainerRequest.ProtoReflect.Descriptor instead.
func (*LaunchContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_nodemanager_proto_rawDescGZIP(), []int{0}
}

func (x *LaunchContainerRequest) GetSpec() *ContainerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type LaunchContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchContainerResponse) Reset() {
	*x = LaunchContainerResponse{}
	mi := &file_proto_nodemanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchContainerResponse) ProtoMessage() {}

func (x *LaunchContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodemanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchContainerResponse.ProtoReflect.Descriptor instead.
func (*LaunchContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_nodemanager_proto_rawDescGZIP(), []int{1}
}

func (x *LaunchContainerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LaunchContainerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerRequest) Reset() {
	*x = StopContainerRequest{}
	mi := &file_proto_nodemanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerRequest) ProtoMessage() {}

func (x *StopContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodemanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerRequest.ProtoReflect.Descriptor instead.
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_nodemanager_proto_rawDescGZIP(), []int{2}
}

func (x *StopContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StopContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerResponse) Reset() {
	*x = StopContainerResponse{}
	mi := &file_proto_nodemanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerResponse) ProtoMessage() {}

func (x *StopContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodemanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerResponse.ProtoReflect.Descriptor instead.
func (*StopContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_nodemanager_proto_rawDescGZIP(), []int{3}
}

func (x *StopContainerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopContainerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetContainerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerStatusRequest) Reset() {
	*x = GetContainerStatusRequest{}
	mi := &file_proto_nodemanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerStatusRequest) ProtoMessage() {}

func (x *GetContainerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodemanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetContainerStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_nodemanager_proto_rawDescGZIP(), []int{4}
}

func (x *GetContainerStatusRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type GetContainerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	State         ContainerState         `protobuf:"varint,2,opt,name=state,proto3,enum=minihadoop.ContainerState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Diagnostics   string                 `protobuf:"bytes,4,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerStatusResponse) Reset() {
	*x = GetContainerStatusResponse{}
	mi := &file_proto_nodemanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerStatusResponse) ProtoMessage() {}

func (x *GetContainerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodemanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetContainerStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_nodemanager_proto_rawDescGZIP(), []int{5}
}

func (x *GetContainerStatusResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *GetContainerStatusResponse) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CONTAINER_STATE_UNSPECIFIED
}

func (x *GetContainerStatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *GetContainerStatusResponse) GetDiagnostics() string {
	if x != nil {
		return x.Diagnostics
	}
	return ""
}

func (x *GetContainerStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_nodemanager_proto protoreflect.FileDescriptor

const file_proto_nodemanager_proto_rawDesc = "" +
	"\n" +
	"\x17proto/nodemanager.proto\x12\n" +
	"minihadoop\x1a\x12proto/common.proto\"G\n" +
	"\x16LaunchContainerRequest\x12-\n" +
	"\x04spec\x18\x01 \x01(\v2\x19.minihadoop.ContainerSpecR\x04spec\"I\n" +
	"\x17LaunchContainerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"9\n" +
	"\x14StopContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"G\n" +
	"\x15StopContainerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\x19GetContainerStatusRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"\xc6\x01\n" +
	"\x1aGetContainerStatusResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.minihadoop.ContainerStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12 \n" +
	"\vdiagnostics\x18\x04 \x01(\tR\vdiagnostics\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2\xab\x02\n" +
	"\x12NodeManagerService\x12Z\n" +
	"\x0fLaunchContainer\x12\".minihadoop.LaunchContainerRequest\x1a#.minihadoop.LaunchContainerResponse\x12T\n" +
	"\rStopContainer\x12 .minihadoop.StopContainerRequest\x1a!.minihadoop.StopContainerResponse\x12c\n" +
	"\x12GetContainerStatus\x12%.minihadoop.GetContainerStatusRequest\x1a&.minihadoop.GetContainerStatusResponseB*Z(github.com/mini-hadoop/mini-hadoop/protob\x06proto3"

var (
	file_proto_nodemanager_proto_rawDescOnce sync.Once
	file_proto_nodemanager_proto_rawDescData []byte
)

func file_proto_nodemanager_proto_rawDescGZIP() []byte {
	file_proto_nodemanager_proto_rawDescOnce.Do(func() {
		file_proto_nodemanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nodemanager_proto_rawDesc), len(file_proto_nodemanager_proto_rawDesc)))
	})
	return file_proto_nodemanager_proto_rawDescData
}

var file_proto_nodemanager_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_nodemanager_proto_goTypes = []any{
	(*LaunchContainerRequest)(nil),     // 0: minihadoop.LaunchContainerRequest
	(*LaunchContainerResponse)(nil),    // 1: minihadoop.LaunchContainerResponse
	(*StopContainerRequest)(nil),       // 2: minihadoop.StopContainerRequest
	(*StopContainerResponse)(nil),      // 3: minihadoop.StopContainerResponse
	(*GetContainerStatusRequest)(nil),  // 4: minihadoop.GetContainerStatusRequest
	(*GetContainerStatusResponse)(nil), // 5: minihadoop.GetContainerStatusResponse
	(*ContainerSpec)(nil),              // 6: minihadoop.ContainerSpec
	(ContainerState)(0),                // 7: minihadoop.ContainerState
}
var file_proto_nodemanager_proto_depIdxs = []int32{
	6, // 0: minihadoop.LaunchContainerRequest.spec:type_name -> minihadoop.ContainerSpec
	7, // 1: minihadoop.GetContainerStatusResponse.state:type_name -> minihadoop.ContainerState
	0, // 2: minihadoop.NodeManagerService.LaunchContainer:input_type -> minihadoop.LaunchContainerRequest
	2, // 3: minihadoop.NodeManagerService.StopContainer:input_type -> minihadoop.StopContainerRequest
	4, // 4: minihadoop.NodeManagerService.GetContainerStatus:input_type -> minihadoop.GetContainerStatusRequest
	1, // 5: minihadoop.NodeManagerService.LaunchContainer:output_type -> minihadoop.LaunchContainerResponse
	3, // 6: minihadoop.NodeManagerService.StopContainer:output_type -> minihadoop.StopContainerResponse
	5, // 7: minihadoop.NodeManagerService.GetContainerStatus:output_type -> minihadoop.GetContainerStatusResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_nodemanager_proto_init() }
func file_proto_nodemanager_proto_init() {
	if File_proto_nodemanager_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nodemanager_proto_rawDesc), len(file_proto_nodemanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nodemanager_proto_goTypes,
		DependencyIndexes: file_proto_nodemanager_proto_depIdxs,
		MessageInfos:      file_proto_nodemanager_proto_msgTypes,
	}.Build()
	File_proto_nodemanager_proto = out.File
	file_proto_nodemanager_proto_goTypes = nil
	file_proto_nodemanager_proto_depIdxs = nil
}
