// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/resourcemanager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerActionType int32

const (
	ContainerActionType_CONTAINER_ACTION_UNSPECIFIED ContainerActionType = 0
	ContainerActionType_KILL_CONTAINER               ContainerActionType = 1
)

// Enum value maps for ContainerActionType.
var (
	ContainerActionType_name = map[int32]string{
		0: "CONTAINER_ACTION_UNSPECIFIED",
		1: "KILL_CONTAINER",
	}
	ContainerActionType_value = map[string]int32{
		"CONTAINER_ACTION_UNSPECIFIED": 0,
		"KILL_CONTAINER":               1,
	}
)

func (x ContainerActionType) Enum() *ContainerActionType {
	p := new(ContainerActionType)
	*p = x
	return p
}

func (x ContainerActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_resourcemanager_proto_enumTypes[0].Descriptor()
}

func (ContainerActionType) Type() protoreflect.EnumType {
	return &file_proto_resourcemanager_proto_enumTypes[0]
}

func (x ContainerActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerActionType.Descriptor instead.
func (ContainerActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{0}
}

type SubmitApplicationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationType string                 `protobuf:"bytes,1,opt,name=application_type,json=applicationType,proto3" json:"application_type,omitempty"`                                             // e.g., "mapreduce"
	AmBinaryPath    string                 `protobuf:"bytes,2,opt,name=am_binary_path,json=amBinaryPath,proto3" json:"am_binary_path,omitempty"`                                                    // Path to ApplicationMaster binary
	AmArgs          []string               `protobuf:"bytes,3,rep,name=am_args,json=amArgs,proto3" json:"am_args,omitempty"`                                                                        // Arguments for the AM binary
	AmMemoryMb      int32                  `protobuf:"varint,4,opt,name=am_memory_mb,json=amMemoryMb,proto3" json:"am_memory_mb,omitempty"`                                                         // Memory for AM container
	AmCpuVcores     int32                  `protobuf:"varint,5,opt,name=am_cpu_vcores,json=amCpuVcores,proto3" json:"am_cpu_vcores,omitempty"`                                                      // CPU for AM container
	AmEnv           map[string]string      `protobuf:"bytes,6,rep,name=am_env,json=amEnv,proto3" json:"am_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables for AM
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitApplicationRequest) Reset() {
	*x = SubmitApplicationRequest{}
	mi := &file_proto_resourcemanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplicationRequest) ProtoMessage() {}

func (x *SubmitApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplicationRequest.ProtoReflect.Descriptor instead.
func (*SubmitApplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitApplicationRequest) GetApplicationType() string {
	if x != nil {
		return x.ApplicationType
	}
	return ""
}

func (x *SubmitApplicationRequest) GetAmBinaryPath() string {
	if x != nil {
		return x.AmBinaryPath
	}
	return ""
}

func (x *SubmitApplicationRequest) GetAmArgs() []string {
	if x != nil {
		return x.AmArgs
	}
	return nil
}

func (x *SubmitApplicationRequest) GetAmMemoryMb() int32 {
	if x != nil {
		return x.AmMemoryMb
	}
	return 0
}

func (x *SubmitApplicationRequest) GetAmCpuVcores() int32 {
	if x != nil {
		return x.AmCpuVcores
	}
	return 0
}

func (x *SubmitApplicationRequest) GetAmEnv() map[string]string {
	if x != nil {
		return x.AmEnv
	}
	return nil
}

type SubmitApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApplicationResponse) Reset() {
	*x = SubmitApplicationResponse{}
	mi := &file_proto_resourcemanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplicationResponse) ProtoMessage() {}

func (x *SubmitApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplicationResponse.ProtoReflect.Descriptor instead.
func (*SubmitApplicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitApplicationResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SubmitApplicationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetApplicationReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationReportRequest) Reset() {
	*x = GetApplicationReportRequest{}
	mi := &file_proto_resourcemanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationReportRequest) ProtoMessage() {}

func (x *GetApplicationReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationReportRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{2}
}

func (x *GetApplicationReportRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetApplicationReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ApplicationStatus     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationReportResponse) Reset() {
	*x = GetApplicationReportResponse{}
	mi := &file_proto_resourcemanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationReportResponse) ProtoMessage() {}

func (x *GetApplicationReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationReportResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{3}
}

func (x *GetApplicationReportResponse) GetStatus() *ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetApplicationReportResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KillApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillApplicationRequest) Reset() {
	*x = KillApplicationRequest{}
	mi := &file_proto_resourcemanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillApplicationRequest) ProtoMessage() {}

func (x *KillApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillApplicationRequest.ProtoReflect.Descriptor instead.
func (*KillApplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{4}
}

func (x *KillApplicationRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type KillApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillApplicationResponse) Reset() {
	*x = KillApplicationResponse{}
	mi := &file_proto_resourcemanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillApplicationResponse) ProtoMessage() {}

func (x *KillApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillApplicationResponse.ProtoReflect.Descriptor instead.
func (*KillApplicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{5}
}

func (x *KillApplicationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KillApplicationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AllocateContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Requests      []*ContainerRequest    `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateContainersRequest) Reset() {
	*x = AllocateContainersRequest{}
	mi := &file_proto_resourcemanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateContainersRequest) ProtoMessage() {}

func (x *AllocateContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateContainersRequest.ProtoReflect.Descriptor instead.
func (*AllocateContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{6}
}

func (x *AllocateContainersRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AllocateContainersRequest) GetRequests() []*ContainerRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryMb      int32                  `protobuf:"varint,1,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	CpuVcores     int32                  `protobuf:"varint,2,opt,name=cpu_vcores,json=cpuVcores,proto3" json:"cpu_vcores,omitempty"`
	Locality      *LocalityPreference    `protobuf:"bytes,3,opt,name=locality,proto3" json:"locality,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`                         // Number of containers with these specs
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Caller's tracking ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRequest) Reset() {
	*x = ContainerRequest{}
	mi := &file_proto_resourcemanager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRequest) ProtoMessage() {}

func (x *ContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRequest.ProtoReflect.Descriptor instead.
func (*ContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ContainerRequest) GetCpuVcores() int32 {
	if x != nil {
		return x.CpuVcores
	}
	return 0
}

func (x *ContainerRequest) GetLocality() *LocalityPreference {
	if x != nil {
		return x.Locality
	}
	return nil
}

func (x *ContainerRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ContainerRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AllocateContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerSpec       `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateContainersResponse) Reset() {
	*x = AllocateContainersResponse{}
	mi := &file_proto_resourcemanager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateContainersResponse) ProtoMessage() {}

func (x *AllocateContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateContainersResponse.ProtoReflect.Descriptor instead.
func (*AllocateContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{8}
}

func (x *AllocateContainersResponse) GetContainers() []*ContainerSpec {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *AllocateContainersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReleaseContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ContainerIds  []string               `protobuf:"bytes,2,rep,name=container_ids,json=containerIds,proto3" json:"container_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseContainersRequest) Reset() {
	*x = ReleaseContainersRequest{}
	mi := &file_proto_resourcemanager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseContainersRequest) ProtoMessage() {}

func (x *ReleaseContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseContainersRequest.ProtoReflect.Descriptor instead.
func (*ReleaseContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseContainersRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ReleaseContainersRequest) GetContainerIds() []string {
	if x != nil {
		return x.ContainerIds
	}
	return nil
}

type ReleaseContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseContainersResponse) Reset() {
	*x = ReleaseContainersResponse{}
	mi := &file_proto_resourcemanager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseContainersResponse) ProtoMessage() {}

func (x *ReleaseContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseContainersResponse.ProtoReflect.Descriptor instead.
func (*ReleaseContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseContainersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseContainersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegisterNodeManagerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TotalMemoryMb int32                  `protobuf:"varint,3,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`
	TotalCpu      int32                  `protobuf:"varint,4,opt,name=total_cpu,json=totalCpu,proto3" json:"total_cpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeManagerRequest) Reset() {
	*x = RegisterNodeManagerRequest{}
	mi := &file_proto_resourcemanager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeManagerRequest) ProtoMessage() {}

func (x *RegisterNodeManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeManagerRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeManagerRequest) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterNodeManagerRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeManagerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterNodeManagerRequest) GetTotalMemoryMb() int32 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

func (x *RegisterNodeManagerRequest) GetTotalCpu() int32 {
	if x != nil {
		return x.TotalCpu
	}
	return 0
}

type RegisterNodeManagerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeManagerResponse) Reset() {
	*x = RegisterNodeManagerResponse{}
	mi := &file_proto_resourcemanager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeManagerResponse) ProtoMessage() {}

func (x *RegisterNodeManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeManagerResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeManagerResponse) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterNodeManagerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeManagerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NodeManagerHeartbeatRequest struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	NodeId            string                   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status            *NodeStatus              `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ContainerStatuses []*ContainerStatusReport `protobuf:"bytes,3,rep,name=container_statuses,json=containerStatuses,proto3" json:"container_statuses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeManagerHeartbeatRequest) Reset() {
	*x = NodeManagerHeartbeatRequest{}
	mi := &file_proto_resourcemanager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeManagerHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeManagerHeartbeatRequest) ProtoMessage() {}

func (x *NodeManagerHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeManagerHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*NodeManagerHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{13}
}

func (x *NodeManagerHeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeManagerHeartbeatRequest) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *NodeManagerHeartbeatRequest) GetContainerStatuses() []*ContainerStatusReport {
	if x != nil {
		return x.ContainerStatuses
	}
	return nil
}

type ContainerStatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	State         ContainerState         `protobuf:"varint,2,opt,name=state,proto3,enum=minihadoop.ContainerState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Diagnostics   string                 `protobuf:"bytes,4,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatusReport) Reset() {
	*x = ContainerStatusReport{}
	mi := &file_proto_resourcemanager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatusReport) ProtoMessage() {}

func (x *ContainerStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatusReport.ProtoReflect.Descriptor instead.
func (*ContainerStatusReport) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{14}
}

func (x *ContainerStatusReport) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerStatusReport) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CONTAINER_STATE_UNSPECIFIED
}

func (x *ContainerStatusReport) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerStatusReport) GetDiagnostics() string {
	if x != nil {
		return x.Diagnostics
	}
	return ""
}

type NodeManagerHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*ContainerAction     `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeManagerHeartbeatResponse) Reset() {
	*x = NodeManagerHeartbeatResponse{}
	mi := &file_proto_resourcemanager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeManagerHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeManagerHeartbeatResponse) ProtoMessage() {}

func (x *NodeManagerHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeManagerHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*NodeManagerHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{15}
}

func (x *NodeManagerHeartbeatResponse) GetActions() []*ContainerAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ContainerAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ContainerActionType    `protobuf:"varint,1,opt,name=type,proto3,enum=minihadoop.ContainerActionType" json:"type,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerAction) Reset() {
	*x = ContainerAction{}
	mi := &file_proto_resourcemanager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerAction) ProtoMessage() {}

func (x *ContainerAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resourcemanager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerAction.ProtoReflect.Descriptor instead.
func (*ContainerAction) Descriptor() ([]byte, []int) {
	return file_proto_resourcemanager_proto_rawDescGZIP(), []int{16}
}

func (x *ContainerAction) GetType() ContainerActionType {
	if x != nil {
		return x.Type
	}
	return ContainerActionType_CONTAINER_ACTION_UNSPECIFIED
}

func (x *ContainerAction) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

var File_proto_resourcemanager_proto protoreflect.FileDescriptor

const file_proto_resourcemanager_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/resourcemanager.proto\x12\n" +
	"minihadoop\x1a\x12proto/common.proto\"\xcc\x02\n" +
	"\x18SubmitApplicationRequest\x12)\n" +
	"\x10application_type\x18\x01 \x01(\tR\x0fapplicationType\x12$\n" +
	"\x0eam_binary_path\x18\x02 \x01(\tR\famBinaryPath\x12\x17\n" +
	"\aam_args\x18\x03 \x03(\tR\x06amArgs\x12 \n" +
	"\fam_memory_mb\x18\x04 \x01(\x05R\n" +
	"amMemoryMb\x12\"\n" +
	"\ram_cpu_vcores\x18\x05 \x01(\x05R\vamCpuVcores\x12F\n" +
	"\x06am_env\x18\x06 \x03(\v2/.minihadoop.SubmitApplicationRequest.AmEnvEntryR\x05amEnv\x1a8\n" +
	"\n" +
	"AmEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x19SubmitApplicationResponse\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x1bGetApplicationReportRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"k\n" +
	"\x1cGetApplicationReportResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.minihadoop.ApplicationStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\x16KillApplicationRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"I\n" +
	"\x17KillApplicationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"l\n" +
	"\x19AllocateContainersRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x128\n" +
	"\brequests\x18\x02 \x03(\v2\x1c.minihadoop.ContainerRequestR\brequests\"\xbf\x01\n" +
	"\x10ContainerRequest\x12\x1b\n" +
	"\tmemory_mb\x18\x01 \x01(\x05R\bmemoryMb\x12\x1d\n" +
	"\n" +
	"cpu_vcores\x18\x02 \x01(\x05R\tcpuVcores\x12:\n" +
	"\blocality\x18\x03 \x01(\v2\x1e.minihadoop.LocalityPreferenceR\blocality\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"m\n" +
	"\x1aAllocateContainersResponse\x129\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x19.minihadoop.ContainerSpecR\n" +
	"containers\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\x18ReleaseContainersRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12#\n" +
	"\rcontainer_ids\x18\x02 \x03(\tR\fcontainerIds\"K\n" +
	"\x19ReleaseContainersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x94\x01\n" +
	"\x1aRegisterNodeManagerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12&\n" +
	"\x0ftotal_memory_mb\x18\x03 \x01(\x05R\rtotalMemoryMb\x12\x1b\n" +
	"\ttotal_cpu\x18\x04 \x01(\x05R\btotalCpu\"M\n" +
	"\x1bRegisterNodeManagerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb8\x01\n" +
	"\x1bNodeManagerHeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\x06status\x18\x02 \x01(\v2\x16.minihadoop.NodeStatusR\x06status\x12P\n" +
	"\x12container_statuses\x18\x03 \x03(\v2!.minihadoop.ContainerStatusReportR\x11containerStatuses\"\xab\x01\n" +
	"\x15ContainerStatusReport\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.minihadoop.ContainerStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12 \n" +
	"\vdiagnostics\x18\x04 \x01(\tR\vdiagnostics\"U\n" +
	"\x1cNodeManagerHeartbeatResponse\x125\n" +
	"\aactions\x18\x01 \x03(\v2\x1b.minihadoop.ContainerActionR\aactions\"i\n" +
	"\x0fContainerAction\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.minihadoop.ContainerActionTypeR\x04type\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId*K\n" +
	"\x13ContainerActionType\x12 \n" +
	"\x1cCONTAINER_ACTION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eKILL_CONTAINER\x10\x012\xdb\x05\n" +
	"\x16ResourceManagerService\x12`\n" +
	"\x11SubmitApplication\x12$.minihadoop.SubmitApplicationRequest\x1a%.minihadoop.SubmitApplicationResponse\x12i\n" +
	"\x14GetApplicationReport\x12'.minihadoop.GetApplicationReportRequest\x1a(.minihadoop.GetApplicationReportResponse\x12Z\n" +
	"\x0fKillApplication\x12\".minihadoop.KillApplicationRequest\x1a#.minihadoop.KillApplicationResponse\x12c\n" +
	"\x12AllocateContainers\x12%.minihadoop.AllocateContainersRequest\x1a&.minihadoop.AllocateContainersResponse\x12`\n" +
	"\x11ReleaseContainers\x12$.minihadoop.ReleaseContainersRequest\x1a%.minihadoop.ReleaseContainersResponse\x12f\n" +
	"\x13RegisterNodeManager\x12&.minihadoop.RegisterNodeManagerRequest\x1a'.minihadoop.RegisterNodeManagerResponse\x12i\n" +
	"\x14NodeManagerHeartbeat\x12'.minihadoop.NodeManagerHeartbeatRequest\x1a(.minihadoop.NodeManagerHeartbeatResponseB*Z(github.com/mini-hadoop/mini-hadoop/protob\x06proto3"

var (
	file_proto_resourcemanager_proto_rawDescOnce sync.Once
	file_proto_resourcemanager_proto_rawDescData []byte
)

func file_proto_resourcemanager_proto_rawDescGZIP() []byte {
	file_proto_resourcemanager_proto_rawDescOnce.Do(func() {
		file_proto_resourcemanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resourcemanager_proto_rawDesc), len(file_proto_resourcemanager_proto_rawDesc)))
	})
	return file_proto_resourcemanager_proto_rawDescData
}

var file_proto_resourcemanager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_resourcemanager_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_resourcemanager_proto_goTypes = []any{
	(ContainerActionType)(0),             // 0: minihadoop.ContainerActionType
	(*SubmitApplicationRequest)(nil),     // 1: minihadoop.SubmitApplicationRequest
	(*SubmitApplicationResponse)(nil),    // 2: minihadoop.SubmitApplicationResponse
	(*GetApplicationReportRequest)(nil),  // 3: minihadoop.GetApplicationReportRequest
	(*GetApplicationReportResponse)(nil), // 4: minihadoop.GetApplicationReportResponse
	(*KillApplicationRequest)(nil),       // 5: minihadoop.KillApplicationRequest
	(*KillApplicationResponse)(nil),      // 6: minihadoop.KillApplicationResponse
	(*AllocateContainersRequest)(nil),    // 7: minihadoop.AllocateContainersRequest
	(*ContainerRequest)(nil),             // 8: minihadoop.ContainerRequest
	(*AllocateContainersResponse)(nil),   // 9: minihadoop.AllocateContainersResponse
	(*ReleaseContainersRequest)(nil),     // 10: minihadoop.ReleaseContainersRequest
	(*ReleaseContainersResponse)(nil),    // 11: minihadoop.ReleaseContainersResponse
	(*RegisterNodeManagerRequest)(nil),   // 12: minihadoop.RegisterNodeManagerRequest
	(*RegisterNodeManagerResponse)(nil),  // 13: minihadoop.RegisterNodeManagerResponse
	(*NodeManagerHeartbeatRequest)(nil),  // 14: minihadoop.NodeManagerHeartbeatRequest
	(*ContainerStatusReport)(nil),        // 15: minihadoop.ContainerStatusReport
	(*NodeManagerHeartbeatResponse)(nil), // 16: minihadoop.NodeManagerHeartbeatResponse
	(*ContainerAction)(nil),              // 17: minihadoop.ContainerAction
	nil,                                  // 18: minihadoop.SubmitApplicationRequest.AmEnvEntry
	(*ApplicationStatus)(nil),            // 19: minihadoop.ApplicationStatus
	(*LocalityPreference)(nil),           // 20: minihadoop.LocalityPreference
	(*ContainerSpec)(nil),                // 21: minihadoop.ContainerSpec
	(*NodeStatus)(nil),                   // 22: minihadoop.NodeStatus
	(ContainerState)(0),                  // 23: minihadoop.ContainerState
}
var file_proto_resourcemanager_proto_depIdxs = []int32{
	18, // 0: minihadoop.SubmitApplicationRequest.am_env:type_name -> minihadoop.SubmitApplicationRequest.AmEnvEntry
	19, // 1: minihadoop.GetApplicationReportResponse.status:type_name -> minihadoop.ApplicationStatus
	8,  // 2: minihadoop.AllocateContainersRequest.requests:type_name -> minihadoop.ContainerRequest
	20, // 3: minihadoop.ContainerRequest.locality:type_name -> minihadoop.LocalityPreference
	21, // 4: minihadoop.AllocateContainersResponse.containers:type_name -> minihadoop.ContainerSpec
	22, // 5: minihadoop.NodeManagerHeartbeatRequest.status:type_name -> minihadoop.NodeStatus
	15, // 6: minihadoop.NodeManagerHeartbeatRequest.container_statuses:type_name -> minihadoop.ContainerStatusReport
	23, // 7: minihadoop.ContainerStatusReport.state:type_name -> minihadoop.ContainerState
	17, // 8: minihadoop.NodeManagerHeartbeatResponse.actions:type_name -> minihadoop.ContainerAction
	0,  // 9: minihadoop.ContainerAction.type:type_name -> minihadoop.ContainerActionType
	1,  // 10: minihadoop.ResourceManagerService.SubmitApplication:input_type -> minihadoop.SubmitApplicationRequest
	3,  // 11: minihadoop.ResourceManagerService.GetApplicationReport:input_type -> minihadoop.GetApplicationReportRequest
	5,  // 12: minihadoop.ResourceManagerService.KillApplication:input_type -> minihadoop.KillApplicationRequest
	7,  // 13: minihadoop.ResourceManagerService.AllocateContainers:input_type -> minihadoop.AllocateContainersRequest
	10, // 14: minihadoop.ResourceManagerService.ReleaseContainers:input_type -> minihadoop.ReleaseContainersRequest
	12, // 15: minihadoop.ResourceManagerService.RegisterNodeManager:input_type -> minihadoop.RegisterNodeManagerRequest
	14, // 16: minihadoop.ResourceManagerService.NodeManagerHeartbeat:input_type -> minihadoop.NodeManagerHeartbeatRequest
	2,  // 17: minihadoop.ResourceManagerService.SubmitApplication:output_type -> minihadoop.SubmitApplicationResponse
	4,  // 18: minihadoop.ResourceManagerService.GetApplicationReport:output_type -> minihadoop.GetApplicationReportResponse
	6,  // 19: minihadoop.ResourceManagerService.KillApplication:output_type -> minihadoop.KillApplicationResponse
	9,  // 20: minihadoop.ResourceManagerService.AllocateContainers:output_type -> minihadoop.AllocateContainersResponse
	11, // 21: minihadoop.ResourceManagerService.ReleaseContainers:output_type -> minihadoop.ReleaseContainersResponse
	13, // 22: minihadoop.ResourceManagerService.RegisterNodeManager:output_type -> minihadoop.RegisterNodeManagerResponse
	16, // 23: minihadoop.ResourceManagerService.NodeManagerHeartbeat:output_type -> minihadoop.NodeManagerHeartbeatResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_resourcemanager_proto_init() }
func file_proto_resourcemanager_proto_init() {
	if File_proto_resourcemanager_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resourcemanager_proto_rawDesc), len(file_proto_resourcemanager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_resourcemanager_proto_goTypes,
		DependencyIndexes: file_proto_resourcemanager_proto_depIdxs,
		EnumInfos:         file_proto_resourcemanager_proto_enumTypes,
		MessageInfos:      file_proto_resourcemanager_proto_msgTypes,
	}.Build()
	File_proto_resourcemanager_proto = out.File
	file_proto_resourcemanager_proto_goTypes = nil
	file_proto_resourcemanager_proto_depIdxs = nil
}
