// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.2
// source: proto/resourcemanager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceManagerService_SubmitApplication_FullMethodName    = "/minihadoop.ResourceManagerService/SubmitApplication"
	ResourceManagerService_GetApplicationReport_FullMethodName = "/minihadoop.ResourceManagerService/GetApplicationReport"
	ResourceManagerService_KillApplication_FullMethodName      = "/minihadoop.ResourceManagerService/KillApplication"
	ResourceManagerService_AllocateContainers_FullMethodName   = "/minihadoop.ResourceManagerService/AllocateContainers"
	ResourceManagerService_ReleaseContainers_FullMethodName    = "/minihadoop.ResourceManagerService/ReleaseContainers"
	ResourceManagerService_RegisterNodeManager_FullMethodName  = "/minihadoop.ResourceManagerService/RegisterNodeManager"
	ResourceManagerService_NodeManagerHeartbeat_FullMethodName = "/minihadoop.ResourceManagerService/NodeManagerHeartbeat"
)

// ResourceManagerServiceClient is the client API for ResourceManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceManagerServiceClient interface {
	// Application lifecycle
	SubmitApplication(ctx context.Context, in *SubmitApplicationRequest, opts ...grpc.CallOption) (*SubmitApplicationResponse, error)
	GetApplicationReport(ctx context.Context, in *GetApplicationReportRequest, opts ...grpc.CallOption) (*GetApplicationReportResponse, error)
	KillApplication(ctx context.Context, in *KillApplicationRequest, opts ...grpc.CallOption) (*KillApplicationResponse, error)
	// Container management (called by ApplicationMaster)
	AllocateContainers(ctx context.Context, in *AllocateContainersRequest, opts ...grpc.CallOption) (*AllocateContainersResponse, error)
	ReleaseContainers(ctx context.Context, in *ReleaseContainersRequest, opts ...grpc.CallOption) (*ReleaseContainersResponse, error)
	// NodeManager registration and heartbeats
	RegisterNodeManager(ctx context.Context, in *RegisterNodeManagerRequest, opts ...grpc.CallOption) (*RegisterNodeManagerResponse, error)
	NodeManagerHeartbeat(ctx context.Context, in *NodeManagerHeartbeatRequest, opts ...grpc.CallOption) (*NodeManagerHeartbeatResponse, error)
}

type resourceManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceManagerServiceClient(cc grpc.ClientConnInterface) ResourceManagerServiceClient {
	return &resourceManagerServiceClient{cc}
}

func (c *resourceManagerServiceClient) SubmitApplication(ctx context.Context, in *SubmitApplicationRequest, opts ...grpc.CallOption) (*SubmitApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitApplicationResponse)
	err := c.cc.Invoke(ctx, ResourceManagerService_SubmitApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceManagerServiceClient) GetApplicationReport(ctx context.Context, in *GetApplicationReportRequest, opts ...grpc.CallOption) (*GetApplicationReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicationReportResponse)
	err := c.cc.Invoke(ctx, ResourceManagerService_GetApplicationReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceManagerServiceClient) KillApplication(ctx context.Context, in *KillApplicationRequest, opts ...grpc.CallOption) (*KillApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillApplicationResponse)
	err := c.cc.Invoke(ctx, ResourceManagerService_KillApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceManagerServiceClient) AllocateContainers(ctx context.Context, in *AllocateContainersRequest, opts ...grpc.CallOption) (*AllocateContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateContainersResponse)
	err := c.cc.Invoke(ctx, ResourceManagerService_AllocateContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceManagerServiceClient) ReleaseContainers(ctx context.Context, in *ReleaseContainersRequest, opts ...grpc.CallOption) (*ReleaseContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseContainersResponse)
	err := c.cc.Invoke(ctx, ResourceManagerService_ReleaseContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceManagerServiceClient) RegisterNodeManager(ctx context.Context, in *RegisterNodeManagerRequest, opts ...grpc.CallOption) (*RegisterNodeManagerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeManagerResponse)
	err := c.cc.Invoke(ctx, ResourceManagerService_RegisterNodeManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceManagerServiceClient) NodeManagerHeartbeat(ctx context.Context, in *NodeManagerHeartbeatRequest, opts ...grpc.CallOption) (*NodeManagerHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeManagerHeartbeatResponse)
	err := c.cc.Invoke(ctx, ResourceManagerService_NodeManagerHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceManagerServiceServer is the server API for ResourceManagerService service.
// All implementations must embed UnimplementedResourceManagerServiceServer
// for forward compatibility.
type ResourceManagerServiceServer interface {
	// Application lifecycle
	SubmitApplication(context.Context, *SubmitApplicationRequest) (*SubmitApplicationResponse, error)
	GetApplicationReport(context.Context, *GetApplicationReportRequest) (*GetApplicationReportResponse, error)
	KillApplication(context.Context, *KillApplicationRequest) (*KillApplicationResponse, error)
	// Container management (called by ApplicationMaster)
	AllocateContainers(context.Context, *AllocateContainersRequest) (*AllocateContainersResponse, error)
	ReleaseContainers(context.Context, *ReleaseContainersRequest) (*ReleaseContainersResponse, error)
	// NodeManager registration and heartbeats
	RegisterNodeManager(context.Context, *RegisterNodeManagerRequest) (*RegisterNodeManagerResponse, error)
	NodeManagerHeartbeat(context.Context, *NodeManagerHeartbeatRequest) (*NodeManagerHeartbeatResponse, error)
	mustEmbedUnimplementedResourceManagerServiceServer()
}

// UnimplementedResourceManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceManagerServiceServer struct{}

func (UnimplementedResourceManagerServiceServer) SubmitApplication(context.Context, *SubmitApplicationRequest) (*SubmitApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitApplication not implemented")
}
func (UnimplementedResourceManagerServiceServer) GetApplicationReport(context.Context, *GetApplicationReportRequest) (*GetApplicationReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationReport not implemented")
}
func (UnimplementedResourceManagerServiceServer) KillApplication(context.Context, *KillApplicationRequest) (*KillApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillApplication not implemented")
}
func (UnimplementedResourceManagerServiceServer) AllocateContainers(context.Context, *AllocateContainersRequest) (*AllocateContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateContainers not implemented")
}
func (UnimplementedResourceManagerServiceServer) ReleaseContainers(context.Context, *ReleaseContainersRequest) (*ReleaseContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseContainers not implemented")
}
func (UnimplementedResourceManagerServiceServer) RegisterNodeManager(context.Context, *RegisterNodeManagerRequest) (*RegisterNodeManagerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNodeManager not implemented")
}
func (UnimplementedResourceManagerServiceServer) NodeManagerHeartbeat(context.Context, *NodeManagerHeartbeatRequest) (*NodeManagerHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeManagerHeartbeat not implemented")
}
func (UnimplementedResourceManagerServiceServer) mustEmbedUnimplementedResourceManagerServiceServer() {
}
func (UnimplementedResourceManagerServiceServer) testEmbeddedByValue() {}

// UnsafeResourceManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceManagerServiceServer will
// result in compilation errors.
type UnsafeResourceManagerServiceServer interface {
	mustEmbedUnimplementedResourceManagerServiceServer()
}

func RegisterResourceManagerServiceServer(s grpc.ServiceRegistrar, srv ResourceManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedResourceManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceManagerService_ServiceDesc, srv)
}

func _ResourceManagerService_SubmitApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServiceServer).SubmitApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceManagerService_SubmitApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServiceServer).SubmitApplication(ctx, req.(*SubmitApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceManagerService_GetApplicationReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServiceServer).GetApplicationReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceManagerService_GetApplicationReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServiceServer).GetApplicationReport(ctx, req.(*GetApplicationReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceManagerService_KillApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServiceServer).KillApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceManagerService_KillApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServiceServer).KillApplication(ctx, req.(*KillApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceManagerService_AllocateContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServiceServer).AllocateContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceManagerService_AllocateContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServiceServer).AllocateContainers(ctx, req.(*AllocateContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceManagerService_ReleaseContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServiceServer).ReleaseContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceManagerService_ReleaseContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServiceServer).ReleaseContainers(ctx, req.(*ReleaseContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceManagerService_RegisterNodeManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServiceServer).RegisterNodeManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceManagerService_RegisterNodeManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServiceServer).RegisterNodeManager(ctx, req.(*RegisterNodeManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceManagerService_NodeManagerHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeManagerHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServiceServer).NodeManagerHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceManagerService_NodeManagerHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServiceServer).NodeManagerHeartbeat(ctx, req.(*NodeManagerHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceManagerService_ServiceDesc is the grpc.ServiceDesc for ResourceManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minihadoop.ResourceManagerService",
	HandlerType: (*ResourceManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitApplication",
			Handler:    _ResourceManagerService_SubmitApplication_Handler,
		},
		{
			MethodName: "GetApplicationReport",
			Handler:    _ResourceManagerService_GetApplicationReport_Handler,
		},
		{
			MethodName: "KillApplication",
			Handler:    _ResourceManagerService_KillApplication_Handler,
		},
		{
			MethodName: "AllocateContainers",
			Handler:    _ResourceManagerService_AllocateContainers_Handler,
		},
		{
			MethodName: "ReleaseContainers",
			Handler:    _ResourceManagerService_ReleaseContainers_Handler,
		},
		{
			MethodName: "RegisterNodeManager",
			Handler:    _ResourceManagerService_RegisterNodeManager_Handler,
		},
		{
			MethodName: "NodeManagerHeartbeat",
			Handler:    _ResourceManagerService_NodeManagerHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/resourcemanager.proto",
}
