// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.2
// source: proto/shuffle.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShuffleService_GetMapOutput_FullMethodName              = "/minihadoop.ShuffleService/GetMapOutput"
	ShuffleService_ReportShuffleFetchFailure_FullMethodName = "/minihadoop.ShuffleService/ReportShuffleFetchFailure"
)

// ShuffleServiceClient is the client API for ShuffleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShuffleServiceClient interface {
	// GetMapOutput streams a specific partition of map output to a reducer.
	GetMapOutput(ctx context.Context, in *GetMapOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MapOutputChunk], error)
	// ReportShuffleFetchFailure notifies the AM that a reducer could not fetch
	// map output from a mapper node (mapper may have died after completing).
	ReportShuffleFetchFailure(ctx context.Context, in *ShuffleFetchFailureRequest, opts ...grpc.CallOption) (*ShuffleFetchFailureResponse, error)
}

type shuffleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShuffleServiceClient(cc grpc.ClientConnInterface) ShuffleServiceClient {
	return &shuffleServiceClient{cc}
}

func (c *shuffleServiceClient) GetMapOutput(ctx context.Context, in *GetMapOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MapOutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShuffleService_ServiceDesc.Streams[0], ShuffleService_GetMapOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetMapOutputRequest, MapOutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShuffleService_GetMapOutputClient = grpc.ServerStreamingClient[MapOutputChunk]

func (c *shuffleServiceClient) ReportShuffleFetchFailure(ctx context.Context, in *ShuffleFetchFailureRequest, opts ...grpc.CallOption) (*ShuffleFetchFailureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShuffleFetchFailureResponse)
	err := c.cc.Invoke(ctx, ShuffleService_ReportShuffleFetchFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShuffleServiceServer is the server API for ShuffleService service.
// All implementations must embed UnimplementedShuffleServiceServer
// for forward compatibility.
type ShuffleServiceServer interface {
	// GetMapOutput streams a specific partition of map output to a reducer.
	GetMapOutput(*GetMapOutputRequest, grpc.ServerStreamingServer[MapOutputChunk]) error
	// ReportShuffleFetchFailure notifies the AM that a reducer could not fetch
	// map output from a mapper node (mapper may have died after completing).
	ReportShuffleFetchFailure(context.Context, *ShuffleFetchFailureRequest) (*ShuffleFetchFailureResponse, error)
	mustEmbedUnimplementedShuffleServiceServer()
}

// UnimplementedShuffleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShuffleServiceServer struct{}

func (UnimplementedShuffleServiceServer) GetMapOutput(*GetMapOutputRequest, grpc.ServerStreamingServer[MapOutputChunk]) error {
	return status.Error(codes.Unimplemented, "method GetMapOutput not implemented")
}
func (UnimplementedShuffleServiceServer) ReportShuffleFetchFailure(context.Context, *ShuffleFetchFailureRequest) (*ShuffleFetchFailureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportShuffleFetchFailure not implemented")
}
func (UnimplementedShuffleServiceServer) mustEmbedUnimplementedShuffleServiceServer() {}
func (UnimplementedShuffleServiceServer) testEmbeddedByValue()                        {}

// UnsafeShuffleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShuffleServiceServer will
// result in compilation errors.
type UnsafeShuffleServiceServer interface {
	mustEmbedUnimplementedShuffleServiceServer()
}

func RegisterShuffleServiceServer(s grpc.ServiceRegistrar, srv ShuffleServiceServer) {
	// If the following call panics, it indicates UnimplementedShuffleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShuffleService_ServiceDesc, srv)
}

func _ShuffleService_GetMapOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMapOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShuffleServiceServer).GetMapOutput(m, &grpc.GenericServerStream[GetMapOutputRequest, MapOutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShuffleService_GetMapOutputServer = grpc.ServerStreamingServer[MapOutputChunk]

func _ShuffleService_ReportShuffleFetchFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShuffleFetchFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShuffleServiceServer).ReportShuffleFetchFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShuffleService_ReportShuffleFetchFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShuffleServiceServer).ReportShuffleFetchFailure(ctx, req.(*ShuffleFetchFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShuffleService_ServiceDesc is the grpc.ServiceDesc for ShuffleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShuffleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minihadoop.ShuffleService",
	HandlerType: (*ShuffleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportShuffleFetchFailure",
			Handler:    _ShuffleService_ReportShuffleFetchFailure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMapOutput",
			Handler:       _ShuffleService_GetMapOutput_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/shuffle.proto",
}
