// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/shuffle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMapOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	MapTaskId     string                 `protobuf:"bytes,2,opt,name=map_task_id,json=mapTaskId,proto3" json:"map_task_id,omitempty"`
	PartitionId   int32                  `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"` // Which reducer partition to fetch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapOutputRequest) Reset() {
	*x = GetMapOutputRequest{}
	mi := &file_proto_shuffle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapOutputRequest) ProtoMessage() {}

func (x *GetMapOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shuffle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapOutputRequest.ProtoReflect.Descriptor instead.
func (*GetMapOutputRequest) Descriptor() ([]byte, []int) {
	return file_proto_shuffle_proto_rawDescGZIP(), []int{0}
}

func (x *GetMapOutputRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetMapOutputRequest) GetMapTaskId() string {
	if x != nil {
		return x.MapTaskId
	}
	return ""
}

func (x *GetMapOutputRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

// MapOutputChunk streams key-value pairs from map output.
type MapOutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Serialized key-value pairs
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapOutputChunk) Reset() {
	*x = MapOutputChunk{}
	mi := &file_proto_shuffle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapOutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapOutputChunk) ProtoMessage() {}

func (x *MapOutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shuffle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapOutputChunk.ProtoReflect.Descriptor instead.
func (*MapOutputChunk) Descriptor() ([]byte, []int) {
	return file_proto_shuffle_proto_rawDescGZIP(), []int{1}
}

func (x *MapOutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MapOutputChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MapOutputChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type ShuffleFetchFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	MapTaskId     string                 `protobuf:"bytes,2,opt,name=map_task_id,json=mapTaskId,proto3" json:"map_task_id,omitempty"`
	ReducerTaskId string                 `protobuf:"bytes,3,opt,name=reducer_task_id,json=reducerTaskId,proto3" json:"reducer_task_id,omitempty"`
	FailedNode    string                 `protobuf:"bytes,4,opt,name=failed_node,json=failedNode,proto3" json:"failed_node,omitempty"` // The mapper node that was unreachable
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShuffleFetchFailureRequest) Reset() {
	*x = ShuffleFetchFailureRequest{}
	mi := &file_proto_shuffle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleFetchFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleFetchFailureRequest) ProtoMessage() {}

func (x *ShuffleFetchFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shuffle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleFetchFailureRequest.ProtoReflect.Descriptor instead.
func (*ShuffleFetchFailureRequest) Descriptor() ([]byte, []int) {
	return file_proto_shuffle_proto_rawDescGZIP(), []int{2}
}

func (x *ShuffleFetchFailureRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ShuffleFetchFailureRequest) GetMapTaskId() string {
	if x != nil {
		return x.MapTaskId
	}
	return ""
}

func (x *ShuffleFetchFailureRequest) GetReducerTaskId() string {
	if x != nil {
		return x.ReducerTaskId
	}
	return ""
}

func (x *ShuffleFetchFailureRequest) GetFailedNode() string {
	if x != nil {
		return x.FailedNode
	}
	return ""
}

func (x *ShuffleFetchFailureRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ShuffleFetchFailureResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged   bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	NewMapLocation string                 `protobuf:"bytes,2,opt,name=new_map_location,json=newMapLocation,proto3" json:"new_map_location,omitempty"` // If map was already re-run, provide new location
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShuffleFetchFailureResponse) Reset() {
	*x = ShuffleFetchFailureResponse{}
	mi := &file_proto_shuffle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleFetchFailureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleFetchFailureResponse) ProtoMessage() {}

func (x *ShuffleFetchFailureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shuffle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleFetchFailureResponse.ProtoReflect.Descriptor instead.
func (*ShuffleFetchFailureResponse) Descriptor() ([]byte, []int) {
	return file_proto_shuffle_proto_rawDescGZIP(), []int{3}
}

func (x *ShuffleFetchFailureResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ShuffleFetchFailureResponse) GetNewMapLocation() string {
	if x != nil {
		return x.NewMapLocation
	}
	return ""
}

func (x *ShuffleFetchFailureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_shuffle_proto protoreflect.FileDescriptor

const file_proto_shuffle_proto_rawDesc = "" +
	"\n" +
	"\x13proto/shuffle.proto\x12\n" +
	"minihadoop\"o\n" +
	"\x13GetMapOutputRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1e\n" +
	"\vmap_task_id\x18\x02 \x01(\tR\tmapTaskId\x12!\n" +
	"\fpartition_id\x18\x03 \x01(\x05R\vpartitionId\"U\n" +
	"\x0eMapOutputChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"\xc1\x01\n" +
	"\x1aShuffleFetchFailureRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1e\n" +
	"\vmap_task_id\x18\x02 \x01(\tR\tmapTaskId\x12&\n" +
	"\x0freducer_task_id\x18\x03 \x01(\tR\rreducerTaskId\x12\x1f\n" +
	"\vfailed_node\x18\x04 \x01(\tR\n" +
	"failedNode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x81\x01\n" +
	"\x1bShuffleFetchFailureResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12(\n" +
	"\x10new_map_location\x18\x02 \x01(\tR\x0enewMapLocation\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xcd\x01\n" +
	"\x0eShuffleService\x12M\n" +
	"\fGetMapOutput\x12\x1f.minihadoop.GetMapOutputRequest\x1a\x1a.minihadoop.MapOutputChunk0\x01\x12l\n" +
	"\x19ReportShuffleFetchFailure\x12&.minihadoop.ShuffleFetchFailureRequest\x1a'.minihadoop.ShuffleFetchFailureResponseB*Z(github.com/mini-hadoop/mini-hadoop/protob\x06proto3"

var (
	file_proto_shuffle_proto_rawDescOnce sync.Once
	file_proto_shuffle_proto_rawDescData []byte
)

func file_proto_shuffle_proto_rawDescGZIP() []byte {
	file_proto_shuffle_proto_rawDescOnce.Do(func() {
		file_proto_shuffle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shuffle_proto_rawDesc), len(file_proto_shuffle_proto_rawDesc)))
	})
	return file_proto_shuffle_proto_rawDescData
}

var file_proto_shuffle_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_shuffle_proto_goTypes = []any{
	(*GetMapOutputRequest)(nil),         // 0: minihadoop.GetMapOutputRequest
	(*MapOutputChunk)(nil),              // 1: minihadoop.MapOutputChunk
	(*ShuffleFetchFailureRequest)(nil),  // 2: minihadoop.ShuffleFetchFailureRequest
	(*ShuffleFetchFailureResponse)(nil), // 3: minihadoop.ShuffleFetchFailureResponse
}
var file_proto_shuffle_proto_depIdxs = []int32{
	0, // 0: minihadoop.ShuffleService.GetMapOutput:input_type -> minihadoop.GetMapOutputRequest
	2, // 1: minihadoop.ShuffleService.ReportShuffleFetchFailure:input_type -> minihadoop.ShuffleFetchFailureRequest
	1, // 2: minihadoop.ShuffleService.GetMapOutput:output_type -> minihadoop.MapOutputChunk
	3, // 3: minihadoop.ShuffleService.ReportShuffleFetchFailure:output_type -> minihadoop.ShuffleFetchFailureResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_shuffle_proto_init() }
func file_proto_shuffle_proto_init() {
	if File_proto_shuffle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shuffle_proto_rawDesc), len(file_proto_shuffle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shuffle_proto_goTypes,
		DependencyIndexes: file_proto_shuffle_proto_depIdxs,
		MessageInfos:      file_proto_shuffle_proto_msgTypes,
	}.Build()
	File_proto_shuffle_proto = out.File
	file_proto_shuffle_proto_goTypes = nil
	file_proto_shuffle_proto_depIdxs = nil
}
